import { API_BASE_URL, USE_MOCK_DATA } from './_shared';

// --- AI Tools ---
export interface IAiRepository {
  summarize(content: string, language?: string): Promise<{ summary: string }>;
}

class MockAiRepository implements IAiRepository {
  async summarize(content: string, language: string = 'ar'): Promise<{ summary: string }> {
    return new Promise(resolve => {
      setTimeout(() => {
        resolve({
          summary: language === 'en'
            ? 'Auto-generated summary: This article covers the latest developments at the ministry, including strategic updates and new projects aimed at improving services for citizens. (This is a demo summary generated by the system)'
            : 'ملخص تلقائي للمقال: يتناول هذا المقال أهم التطورات الأخيرة في الوزارة، بما في ذلك التحديثات الاستراتيجية والمشاريع الجديدة التي تهدف إلى تحسين الخدمات المقدمة للمواطنين. (هذا ملخص تجريبي تم إنشاؤه بواسطة النظام)'
        });
      }, 1500);
    });
  }
}

class ApiAiRepository implements IAiRepository {
  async summarize(content: string, language: string = 'ar'): Promise<{ summary: string }> {
    const text = (content || '').trim();
    if (!text) {
      throw new Error(language === 'ar' ? 'لا يوجد محتوى للتلخيص' : 'No content to summarize');
    }

    // Use Next.js rewrite proxy to AI service (not the Laravel API)
    const res = await fetch(`/ai/summarize`, {
      method: 'POST',
      headers: { 'Content-Type': 'application/json', 'Accept': 'application/json' },
      body: JSON.stringify({ text, language, max_length: 500 }),
    });
    if (!res.ok) {
      const errorData = await res.json().catch(() => null);
      throw new Error(errorData?.detail || (language === 'ar' ? 'فشل في إنشاء الملخص' : 'Failed to generate summary'));
    }
    return res.json();
  }
}


export const createAiRepository = () =>
  USE_MOCK_DATA ? new MockAiRepository() : new ApiAiRepository();
