<?php

namespace Database\Seeders;

use App\Models\Investment;
use Illuminate\Database\Seeder;

class InvestmentSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $investments = [
            // Opportunities
            [
                'title_ar' => 'مشروع الطاقة الشمسية - ريف دمشق',
                'title_en' => 'Solar Energy Project - Damascus Countryside',
                'description_ar' => 'مشروع إنتاج الطاقة الشمسية بقدرة 50 ميغاواط لتزويد المنطقة الصناعية بالطاقة النظيفة',
                'description_en' => 'Solar energy production project with 50MW capacity to supply the industrial zone with clean energy',
                'sector_ar' => 'الطاقة المتجددة',
                'sector_en' => 'Renewable Energy',
                'location_ar' => 'ريف دمشق',
                'location_en' => 'Damascus Countryside',
                'investment_amount' => 5000000,
                'currency' => 'USD',
                'status' => 'available',
                'category' => 'opportunities',
                'icon' => 'Zap',
                'is_featured' => true,
                'order' => 1,
            ],
            [
                'title_ar' => 'مجمع صناعي متكامل - حلب',
                'title_en' => 'Integrated Industrial Complex - Aleppo',
                'description_ar' => 'مجمع صناعي يضم مصانع للنسيج والغذاء والصناعات التحويلية',
                'description_en' => 'Industrial complex including textile, food, and manufacturing factories',
                'sector_ar' => 'الصناعة',
                'sector_en' => 'Industry',
                'location_ar' => 'حلب',
                'location_en' => 'Aleppo',
                'investment_amount' => 15000000,
                'currency' => 'USD',
                'status' => 'available',
                'category' => 'opportunities',
                'icon' => 'Factory',
                'is_featured' => true,
                'order' => 2,
            ],
            [
                'title_ar' => 'مشروع سياحي - اللاذقية',
                'title_en' => 'Tourism Project - Latakia',
                'description_ar' => 'منتجع سياحي على الساحل السوري يضم فندق 5 نجوم ومرافق ترفيهية',
                'description_en' => 'Coastal resort with 5-star hotel and recreational facilities',
                'sector_ar' => 'السياحة',
                'sector_en' => 'Tourism',
                'location_ar' => 'اللاذقية',
                'location_en' => 'Latakia',
                'investment_amount' => 8000000,
                'currency' => 'USD',
                'status' => 'under_review',
                'category' => 'opportunities',
                'icon' => 'Building',
                'order' => 3,
            ],
            [
                'title_ar' => 'مصنع أدوية - حمص',
                'title_en' => 'Pharmaceutical Factory - Homs',
                'description_ar' => 'مصنع لإنتاج الأدوية الأساسية والمستلزمات الطبية',
                'description_en' => 'Factory for producing essential medicines and medical supplies',
                'sector_ar' => 'الصحة',
                'sector_en' => 'Healthcare',
                'location_ar' => 'حمص',
                'location_en' => 'Homs',
                'investment_amount' => 12000000,
                'currency' => 'USD',
                'status' => 'available',
                'category' => 'opportunities',
                'icon' => 'Shield',
                'order' => 4,
            ],
            [
                'title_ar' => 'مشروع زراعي - الحسكة',
                'title_en' => 'Agricultural Project - Al-Hasakah',
                'description_ar' => 'مشروع زراعي متكامل لإنتاج القمح والشعير مع أنظمة ري حديثة',
                'description_en' => 'Integrated agricultural project for wheat and barley production with modern irrigation',
                'sector_ar' => 'الزراعة',
                'sector_en' => 'Agriculture',
                'location_ar' => 'الحسكة',
                'location_en' => 'Al-Hasakah',
                'investment_amount' => 3500000,
                'currency' => 'USD',
                'status' => 'available',
                'category' => 'opportunities',
                'icon' => 'Wheat',
                'order' => 5,
            ],
            [
                'title_ar' => 'مركز تجاري - دمشق',
                'title_en' => 'Commercial Center - Damascus',
                'description_ar' => 'مركز تجاري حديث في قلب العاصمة يضم محلات ومطاعم ومكاتب',
                'description_en' => 'Modern commercial center in the heart of the capital with shops, restaurants, and offices',
                'sector_ar' => 'التجارة',
                'sector_en' => 'Commerce',
                'location_ar' => 'دمشق',
                'location_en' => 'Damascus',
                'investment_amount' => 20000000,
                'currency' => 'USD',
                'status' => 'available',
                'category' => 'opportunities',
                'icon' => 'Building2',
                'is_featured' => true,
                'order' => 6,
            ],

            // One-Stop Shop Services
            [
                'title_ar' => 'تسجيل الشركات',
                'title_en' => 'Company Registration',
                'description_ar' => 'تسجيل الشركات الجديدة وتحديث بيانات الشركات القائمة',
                'description_en' => 'Register new companies and update existing company data',
                'sector_ar' => 'خدمات الأعمال',
                'sector_en' => 'Business Services',
                'location_ar' => 'دمشق',
                'location_en' => 'Damascus',
                'status' => 'available',
                'category' => 'one-stop',
                'icon' => 'FileText',
                'processing_time' => '3-5 أيام عمل',
                'order' => 1,
            ],
            [
                'title_ar' => 'الحصول على التراخيص',
                'title_en' => 'License Acquisition',
                'description_ar' => 'استخراج جميع التراخيص اللازمة لمزاولة النشاط التجاري',
                'description_en' => 'Obtain all necessary licenses for business operations',
                'sector_ar' => 'خدمات الأعمال',
                'sector_en' => 'Business Services',
                'location_ar' => 'دمشق',
                'location_en' => 'Damascus',
                'status' => 'available',
                'category' => 'one-stop',
                'icon' => 'FileCheck',
                'processing_time' => '5-10 أيام عمل',
                'order' => 2,
            ],
            [
                'title_ar' => 'التسجيل الضريبي',
                'title_en' => 'Tax Registration',
                'description_ar' => 'التسجيل في الدوائر المالية والحصول على الرقم الضريبي',
                'description_en' => 'Register with financial departments and obtain tax number',
                'sector_ar' => 'الخدمات المالية',
                'sector_en' => 'Financial Services',
                'location_ar' => 'دمشق',
                'location_en' => 'Damascus',
                'status' => 'available',
                'category' => 'one-stop',
                'icon' => 'Banknote',
                'processing_time' => '2-3 أيام عمل',
                'order' => 3,
            ],
            [
                'title_ar' => 'تراخيص البناء',
                'title_en' => 'Building Permits',
                'description_ar' => 'الحصول على رخص البناء للمشاريع الاستثمارية',
                'description_en' => 'Obtain building permits for investment projects',
                'sector_ar' => 'العقارات',
                'sector_en' => 'Real Estate',
                'location_ar' => 'جميع المحافظات',
                'location_en' => 'All Governorates',
                'status' => 'available',
                'category' => 'one-stop',
                'icon' => 'Building2',
                'processing_time' => '10-15 يوم عمل',
                'order' => 4,
            ],
            [
                'title_ar' => 'التأمينات الاجتماعية',
                'title_en' => 'Social Insurance',
                'description_ar' => 'تسجيل العمال في التأمينات الاجتماعية',
                'description_en' => 'Register workers in social insurance',
                'sector_ar' => 'الموارد البشرية',
                'sector_en' => 'Human Resources',
                'location_ar' => 'دمشق',
                'location_en' => 'Damascus',
                'status' => 'available',
                'category' => 'one-stop',
                'icon' => 'Users',
                'processing_time' => '1-2 يوم عمل',
                'order' => 5,
            ],
            [
                'title_ar' => 'الخدمات الجمركية',
                'title_en' => 'Customs Services',
                'description_ar' => 'تسهيلات الاستيراد والتصدير والإعفاءات الجمركية',
                'description_en' => 'Import and export facilitation and customs exemptions',
                'sector_ar' => 'التجارة الخارجية',
                'sector_en' => 'Foreign Trade',
                'location_ar' => 'المنافذ الحدودية',
                'location_en' => 'Border Crossings',
                'status' => 'available',
                'category' => 'one-stop',
                'icon' => 'Truck',
                'processing_time' => '3-7 أيام عمل',
                'order' => 6,
            ],

            // Investment Licenses
            [
                'title_ar' => 'رخصة استثمار صناعي',
                'title_en' => 'Industrial Investment License',
                'description_ar' => 'رخصة لإنشاء وتشغيل المشاريع الصناعية',
                'description_en' => 'License for establishing and operating industrial projects',
                'sector_ar' => 'الصناعة',
                'sector_en' => 'Industry',
                'location_ar' => 'جميع المحافظات',
                'location_en' => 'All Governorates',
                'status' => 'available',
                'category' => 'licenses',
                'icon' => 'Factory',
                'fee' => '50,000 ل.س',
                'requirements' => json_encode(['ar' => ['طلب رسمي', 'دراسة جدوى', 'السجل التجاري', 'شهادة بيئية'], 'en' => ['Official application', 'Feasibility study', 'Commercial register', 'Environmental certificate']]),
                'order' => 1,
            ],
            [
                'title_ar' => 'رخصة استثمار سياحي',
                'title_en' => 'Tourism Investment License',
                'description_ar' => 'رخصة لإنشاء المشاريع السياحية والفندقية',
                'description_en' => 'License for establishing tourism and hotel projects',
                'sector_ar' => 'السياحة',
                'sector_en' => 'Tourism',
                'location_ar' => 'جميع المحافظات',
                'location_en' => 'All Governorates',
                'status' => 'available',
                'category' => 'licenses',
                'icon' => 'Building',
                'fee' => '75,000 ل.س',
                'requirements' => json_encode(['ar' => ['طلب رسمي', 'مخطط المشروع', 'موافقة وزارة السياحة'], 'en' => ['Official application', 'Project plan', 'Ministry of Tourism approval']]),
                'order' => 2,
            ],
            [
                'title_ar' => 'رخصة استثمار زراعي',
                'title_en' => 'Agricultural Investment License',
                'description_ar' => 'رخصة للمشاريع الزراعية والحيوانية',
                'description_en' => 'License for agricultural and livestock projects',
                'sector_ar' => 'الزراعة',
                'sector_en' => 'Agriculture',
                'location_ar' => 'جميع المحافظات',
                'location_en' => 'All Governorates',
                'status' => 'available',
                'category' => 'licenses',
                'icon' => 'Wheat',
                'fee' => '25,000 ل.س',
                'requirements' => json_encode(['ar' => ['طلب رسمي', 'وثائق الملكية', 'موافقة وزارة الزراعة'], 'en' => ['Official application', 'Ownership documents', 'Ministry of Agriculture approval']]),
                'order' => 3,
            ],
            [
                'title_ar' => 'رخصة استثمار تجاري',
                'title_en' => 'Commercial Investment License',
                'description_ar' => 'رخصة للمشاريع التجارية والمراكز التجارية',
                'description_en' => 'License for commercial projects and shopping centers',
                'sector_ar' => 'التجارة',
                'sector_en' => 'Commerce',
                'location_ar' => 'جميع المحافظات',
                'location_en' => 'All Governorates',
                'status' => 'available',
                'category' => 'licenses',
                'icon' => 'Briefcase',
                'fee' => '40,000 ل.س',
                'requirements' => json_encode(['ar' => ['طلب رسمي', 'السجل التجاري', 'شهادة الغرفة التجارية'], 'en' => ['Official application', 'Commercial register', 'Chamber of Commerce certificate']]),
                'order' => 4,
            ],

            // Investment Guide items
            [
                'title_ar' => 'قانون الاستثمار رقم 18',
                'title_en' => 'Investment Law No. 18',
                'description_ar' => 'القانون الجديد للاستثمار الذي يقدم حوافز وإعفاءات للمستثمرين',
                'description_en' => 'New investment law providing incentives and exemptions for investors',
                'sector_ar' => 'القانون',
                'sector_en' => 'Legal',
                'location_ar' => 'سوريا',
                'location_en' => 'Syria',
                'status' => 'available',
                'category' => 'guide',
                'icon' => 'FileText',
                'order' => 1,
            ],
            [
                'title_ar' => 'الحوافز الاستثمارية',
                'title_en' => 'Investment Incentives',
                'description_ar' => 'تعرف على الحوافز والإعفاءات الضريبية والجمركية للمستثمرين',
                'description_en' => 'Learn about tax and customs incentives and exemptions for investors',
                'sector_ar' => 'الحوافز',
                'sector_en' => 'Incentives',
                'location_ar' => 'سوريا',
                'location_en' => 'Syria',
                'status' => 'available',
                'category' => 'guide',
                'icon' => 'TrendingUp',
                'order' => 2,
            ],
        ];

        foreach ($investments as $investment) {
            Investment::updateOrCreate(
                ['title_ar' => $investment['title_ar'], 'category' => $investment['category']],
                $investment
            );
        }

        $this->command->info('Seeded ' . count($investments) . ' investments successfully!');
    }
}
