<?php

namespace Database\Seeders;

use App\Models\SystemSetting;
use Illuminate\Database\Seeder;

class SettingsSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $settings = [
            [
                'key' => 'announcements_homepage_count',
                'value' => '9',
                'type' => 'integer',
                'group' => 'ui',
                'label_ar' => 'عدد الإعلانات في الصفحة الرئيسية',
                'label_en' => 'Announcements Count (Homepage)',
                'description_ar' => 'عدد بطاقات الإعلانات التي تظهر في شبكة الإعلانات بالصفحة الرئيسية',
                'description_en' => 'Number of announcement cards displayed in the homepage grid',
                'is_public' => true,
                'is_encrypted' => false,
                'settings' => ['min' => 3, 'max' => 30, 'step' => 3],
            ],
            [
                'key' => 'featured_directorates_count',
                'value' => '3',
                'type' => 'integer',
                'group' => 'ui',
                'label_ar' => 'عدد المديريات المميزة',
                'label_en' => 'Featured Directorates Count',
                'is_public' => true,
                'is_encrypted' => false,
                'settings' => ['min' => 3, 'max' => 6],
            ],
            [
                 'key' => 'suggestions_enabled',
                 'value' => 'true',
                 'type' => 'boolean',
                 'group' => 'feature_flags',
                 'label_ar' => 'تفعيل بوابة المقترحات',
                 'label_en' => 'Enable Suggestions Portal',
                 'is_public' => true,
                 'is_encrypted' => false,
            ],
            [
                 'key' => 'investment_section_enabled',
                 'value' => 'true',
                 'type' => 'boolean',
                 'group' => 'feature_flags',
                 'label_ar' => 'عرض قسم الاستثمار في الصفحة الرئيسية',
                 'label_en' => 'Show Investment Section on Homepage',
                 'is_public' => true,
                 'is_encrypted' => false,
            ],
            // Rules & Regulations
            [
                'key' => 'complaint_rules_ar',
                'value' => 'يرجى الالتزام بالمصداقية والموضوعية عند تقديم الشكوى...',
                'type' => 'text',
                'group' => 'rules',
                'label_ar' => 'شروط تقديم الشكاوى (بالعربية)',
                'label_en' => 'Complaint Submission Rules (Arabic)',
                'is_public' => true,
                'is_encrypted' => false,
            ],
            [
                'key' => 'complaint_rules_en',
                'value' => 'Please adhere to credibility and objectivity when submitting a complaint...',
                'type' => 'text',
                'group' => 'rules',
                'label_ar' => 'شروط تقديم الشكاوى (بالإنجليزية)',
                'label_en' => 'Complaint Submission Rules (English)',
                'is_public' => true,
                'is_encrypted' => false,
            ],
            [
                'key' => 'suggestion_rules_ar',
                'value' => 'نرحب بمقترحاتكم البناءة لتطوير العمل...',
                'type' => 'text',
                'group' => 'rules',
                'label_ar' => 'شروط تقديم المقترحات (بالعربية)',
                'label_en' => 'Suggestion Submission Rules (Arabic)',
                'is_public' => true,
                'is_encrypted' => false,
            ],
            [
                'key' => 'suggestion_rules_en',
                'value' => 'We welcome your constructive suggestions to improve our work...',
                'type' => 'text',
                'group' => 'rules',
                'label_ar' => 'شروط تقديم المقترحات (بالإنجليزية)',
                'label_en' => 'Suggestion Submission Rules (English)',
                'is_public' => true,
                'is_encrypted' => false,
            ],
            // Contact Information
            [
                'key' => 'contact_phone',
                'value' => '19999',
                'type' => 'string',
                'group' => 'contact',
                'label_ar' => 'رقم الهاتف',
                'label_en' => 'Phone Number',
                'is_public' => true,
                'is_encrypted' => false,
            ],
            [
                'key' => 'contact_email',
                'value' => 'info@moe.gov.sy',
                'type' => 'string',
                'group' => 'contact',
                'label_ar' => 'البريد الإلكتروني',
                'label_en' => 'Email Address',
                'is_public' => true,
                'is_encrypted' => false,
            ],
            [
                'key' => 'contact_support_email',
                'value' => 'support@moe.gov.sy',
                'type' => 'string',
                'group' => 'contact',
                'label_ar' => 'بريد الدعم الفني',
                'label_en' => 'Support Email',
                'is_public' => true,
                'is_encrypted' => false,
            ],
            [
                'key' => 'contact_address_ar',
                'value' => 'دمشق - ساحة المحافظة - مبنى وزارة الاقتصاد والصناعة',
                'type' => 'string',
                'group' => 'contact',
                'label_ar' => 'العنوان بالعربية',
                'label_en' => 'Address (Arabic)',
                'is_public' => true,
                'is_encrypted' => false,
            ],
            [
                'key' => 'contact_address_en',
                'value' => 'Damascus - Governorate Square - Ministry of Economy and Industry Building',
                'type' => 'string',
                'group' => 'contact',
                'label_ar' => 'العنوان بالإنجليزية',
                'label_en' => 'Address (English)',
                'is_public' => true,
                'is_encrypted' => false,
            ],
            [
                'key' => 'contact_whatsapp',
                'value' => '963912345678',
                'type' => 'string',
                'group' => 'contact',
                'label_ar' => 'رقم واتساب',
                'label_en' => 'WhatsApp Number',
                'is_public' => true,
                'is_encrypted' => false,
            ],
            [
                'key' => 'contact_working_hours_ar',
                'value' => 'الأحد - الخميس: 8:00 صباحاً - 3:30 عصراً',
                'type' => 'string',
                'group' => 'contact',
                'label_ar' => 'ساعات العمل بالعربية',
                'label_en' => 'Working Hours (Arabic)',
                'is_public' => true,
                'is_encrypted' => false,
            ],
            [
                'key' => 'contact_working_hours_en',
                'value' => 'Sunday - Thursday: 8:00 AM - 3:30 PM',
                'type' => 'string',
                'group' => 'contact',
                'label_ar' => 'ساعات العمل بالإنجليزية',
                'label_en' => 'Working Hours (English)',
                'is_public' => true,
                'is_encrypted' => false,
            ],
            // Homepage Statistics
            [
                'key' => 'stat_total_services',
                'value' => '1500',
                'type' => 'integer',
                'group' => 'stats',
                'label_ar' => 'إجمالي الخدمات',
                'label_en' => 'Total Services',
                'is_public' => true,
                'is_encrypted' => false,
            ],
            [
                'key' => 'stat_transactions',
                'value' => '250000',
                'type' => 'integer',
                'group' => 'stats',
                'label_ar' => 'المعاملات المنجزة',
                'label_en' => 'Completed Transactions',
                'is_public' => true,
                'is_encrypted' => false,
            ],
            [
                'key' => 'stat_complaints_resolved',
                'value' => '45000',
                'type' => 'integer',
                'group' => 'stats',
                'label_ar' => 'الشكاوى المحلولة',
                'label_en' => 'Complaints Resolved',
                'is_public' => true,
                'is_encrypted' => false,
            ],
            [
                'key' => 'stat_satisfaction',
                'value' => '94',
                'type' => 'integer',
                'group' => 'stats',
                'label_ar' => 'نسبة الرضا',
                'label_en' => 'Satisfaction Rate',
                'is_public' => true,
                'is_encrypted' => false,
            ],
            // About Page Content
            [
                'key' => 'about_mission_ar',
                'value' => 'تعمل وزارة الاقتصاد والصناعة على تعزيز النمو الاقتصادي المستدام ودعم القطاعات الإنتاجية من خلال سياسات اقتصادية فعّالة وبيئة استثمارية محفزة وخدمات رقمية متطورة.',
                'type' => 'text',
                'group' => 'about',
                'label_ar' => 'الرسالة بالعربية',
                'label_en' => 'Mission (Arabic)',
                'is_public' => true,
                'is_encrypted' => false,
            ],
            [
                'key' => 'about_mission_en',
                'value' => 'The Ministry of Economy and Industry works to promote sustainable economic growth and support productive sectors through effective economic policies, a stimulating investment environment, and advanced Services.',
                'type' => 'text',
                'group' => 'about',
                'label_ar' => 'الرسالة بالإنجليزية',
                'label_en' => 'Mission (English)',
                'is_public' => true,
                'is_encrypted' => false,
            ],
            [
                'key' => 'about_vision_ar',
                'value' => 'اقتصاد وطني متنوع ومستدام يحقق الرفاه للمواطنين ويعزز مكانة سوريا في الاقتصاد العالمي.',
                'type' => 'text',
                'group' => 'about',
                'label_ar' => 'الرؤية بالعربية',
                'label_en' => 'Vision (Arabic)',
                'is_public' => true,
                'is_encrypted' => false,
            ],
            [
                'key' => 'about_vision_en',
                'value' => 'A diversified and sustainable national economy that achieves welfare for citizens and strengthens Syria\'s position in the global economy.',
                'type' => 'text',
                'group' => 'about',
                'label_ar' => 'الرؤية بالإنجليزية',
                'label_en' => 'Vision (English)',
                'is_public' => true,
                'is_encrypted' => false,
            ],
            [
                'key' => 'about_values',
                'value' => json_encode([
                    ['icon' => 'Eye', 'title_ar' => 'الشفافية', 'title_en' => 'Transparency', 'desc_ar' => 'نلتزم بأعلى معايير الشفافية والنزاهة في جميع عملياتنا وقراراتنا.', 'desc_en' => 'We adhere to the highest standards of transparency and integrity in all our operations and decisions.'],
                    ['icon' => 'Award', 'title_ar' => 'التميّز', 'title_en' => 'Excellence', 'desc_ar' => 'نسعى لتقديم خدمات متميزة تلبي تطلعات المواطنين والمستثمرين.', 'desc_en' => 'We strive to provide distinguished services that meet the aspirations of citizens and investors.'],
                    ['icon' => 'Shield', 'title_ar' => 'المسؤولية', 'title_en' => 'Responsibility', 'desc_ar' => 'نتحمل مسؤولية تحقيق التنمية الاقتصادية المستدامة للوطن والمواطن.', 'desc_en' => 'We bear the responsibility of achieving sustainable economic development for the nation and its citizens.'],
                    ['icon' => 'Lightbulb', 'title_ar' => 'الابتكار', 'title_en' => 'Innovation', 'desc_ar' => 'نتبنى الحلول المبتكرة والتقنيات الحديثة لتطوير بيئة الأعمال.', 'desc_en' => 'We adopt innovative solutions and modern technologies to develop the business environment.'],
                ]),
                'type' => 'json',
                'group' => 'about',
                'label_ar' => 'القيم الأساسية',
                'label_en' => 'Core Values',
                'is_public' => true,
                'is_encrypted' => false,
            ],
            [
                'key' => 'about_goals',
                'value' => json_encode([
                    ['title_ar' => 'تطوير القطاع الصناعي وزيادة الإنتاج المحلي', 'title_en' => 'Develop the industrial sector and increase local production'],
                    ['title_ar' => 'تحسين بيئة الأعمال وجذب الاستثمارات', 'title_en' => 'Improve the business environment and attract investments'],
                    ['title_ar' => 'حماية المستهلك وضبط الأسواق', 'title_en' => 'Protect consumers and regulate markets'],
                    ['title_ar' => 'تعزيز التجارة الخارجية والصادرات السورية', 'title_en' => 'Strengthen foreign trade and Syrian exports'],
                    ['title_ar' => 'التحول الرقمي للخدمات الحكومية', 'title_en' => 'Digital transformation of government services'],
                ]),
                'type' => 'json',
                'group' => 'about',
                'label_ar' => 'الأهداف الاستراتيجية',
                'label_en' => 'Strategic Goals',
                'is_public' => true,
                'is_encrypted' => false,
            ]
        ];

        foreach ($settings as $setting) {
            SystemSetting::updateOrCreate(
                ['key' => $setting['key']],
                $setting
            );
        }
    }
}
