'use client';

import React, { createContext, useContext, useState, useEffect, ReactNode } from 'react';

type Language = 'ar' | 'en';
type Direction = 'rtl' | 'ltr';

interface LanguageContextType {
  language: Language;
  direction: Direction;
  toggleLanguage: () => void;
  t: (key: string) => string;
}

const translations: Record<string, Record<Language, string>> = {
  // Brand
  'republic_name': { ar: 'الجمهورية العربية السورية', en: 'Syrian Arab Republic' },
  'ministry_name': { ar: 'وزارة الاقتصاد والصناعة', en: 'Ministry of Economy and Industry' },
  'portal_name': { ar: 'البوابة الإلكترونية', en: 'E-Government Portal' },
  'cabinet': { ar: 'وزارة الاقتصاد والصناعة', en: 'Ministry of Economy and Industry' },
  'unified_platform': { ar: 'المنصة الوطنية الموحدة للخدمات الحكومية', en: 'The Unified National Platform for E-Government Services' },
  'secure_gateway': { ar: 'بوابة آمنة، خدمات متكاملة، ومستقبل رقمي', en: 'Secure Gateway, Integrated Services, Digital Future' },
  'integrated_services': { ar: 'خدمات متكاملة', en: 'Integrated Services' },
  'digital_future': { ar: 'مستقبل رقمي', en: 'Digital Future' },
  'suggestions_section_title': { ar: 'شاركنا أفكارك لتطوير المستقبل', en: 'Share Your Ideas to Shape the Future' },
  'suggestions_section_desc': { ar: 'نؤمن بأن الابتكار يبدأ بفكرة. شارك مقترحاتك ومشاريعك لتساهم معنا في تحسين بيئة الأعمال والخدمات.', en: 'We believe innovation starts with an idea. Share your proposals and projects to help us improve the business environment and services.' },
  'submit_suggestion': { ar: 'مشاركة مقترح', en: 'Share Suggestion' },

  // Nav
  'nav_home': { ar: 'الرئيسية', en: 'Home' },
  'nav_all': { ar: 'الكل', en: 'All' },
  'nav_news': { ar: 'الأخبار', en: 'News' },
  'nav_directory': { ar: 'دليل الجهات', en: 'Directory' },
  'nav_decrees': { ar: 'القوانين والتشريعات', en: 'Laws & Legislation' },
  'nav_complaints': { ar: 'منظومة الشكاوى', en: 'Complaints' },
  'nav_suggestions': { ar: 'المقترحات', en: 'Suggestions' },
  'nav_search': { ar: 'بحث', en: 'Search' },
  'nav_about': { ar: 'عن الوزارة', en: 'About Ministry' },
  'nav_services_legislations': { ar: 'الخدمات والتشريعات', en: 'Services & Legislations' },
  'nav_ministry_services': { ar: 'خدمات الوزارة', en: 'Ministry Services' },
  'nav_industrial_services': { ar: 'خدمات الإدارة العامة للصناعة', en: 'Industrial Services' },
  'nav_economy_services': { ar: 'خدمات الإدارة العامة للاقتصاد', en: 'Economy Services' },
  'nav_trade_services': { ar: 'خدمات التجارة الداخلية', en: 'Internal Trade Services' },
  'nav_media': { ar: 'المركز الإعلامي', en: 'Media Center' },
  'nav_suggestions_complaints': { ar: 'الاقتراحات والشكاوى', en: 'Suggestions & Complaints' },
  'nav_departments': { ar: 'الإدارات', en: 'Departments' },
  'nav_administrations': { ar: 'الإدارات العامة', en: 'General Administrations' },
  'nav_directorates': { ar: 'الهيكل التنظيمي', en: 'Organizational Structure' },
  'nav_sub_directorates': { ar: 'المديريات الفرعية', en: 'Sub-Directorates' },
  'nav_contact_directorate': { ar: 'تواصل مع الإدارة', en: 'Contact Directorate' },
  'nav_for_users': { ar: 'للمستخدمين', en: 'For Users' },
  'nav_feedback': { ar: 'الملاحظات', en: 'Feedback' },
  'nav_investors': { ar: 'للمستثمرين', en: 'For Investors' },
  'nav_citizens': { ar: 'للمواطنين', en: 'For Citizens' },

  // Hero
  'hero_services_btn': { ar: 'دليل الخدمات', en: 'Services Guide' },
  'hero_decrees_btn': { ar: 'القوانين والتشريعات', en: 'Laws & Legislation' },
  'stat_services': { ar: 'خدمة', en: 'E-Services' },
  'stat_secure': { ar: 'بوابة آمنة', en: 'Secure Portal' },
  'stat_transparency': { ar: 'شفافية البيانات', en: 'Data Transparency' },

  // Directorates
  'dir_title_full': { ar: 'دليل الجهات الحكومية', en: 'Government Directory' },
  'dir_subtitle_full': { ar: 'تصفح الدليل الشامل للوزارات والهيئات الحكومية والخدمات الرقمية.', en: 'Browse the comprehensive directory of ministries, agencies, and Services.' },
  'dir_title_compact': { ar: 'الوصول السريع للجهات', en: 'Quick Access' },
  'dir_subtitle_compact': { ar: 'الإدارات التابعة لوزارة الاقتصاد والصناعة', en: 'Directorates of the Ministry of Economy and Industry' },
  'dir_services_selected': { ar: 'خدمات مختارة', en: 'Selected Services' },
  'search_placeholder': { ar: 'ابحث عن محتوى', en: 'Search for content' },
  'view_details': { ar: 'تصفح', en: 'View' },
  'view_all_dirs': { ar: 'عرض دليل الجهات الكامل', en: 'View Full Directory' },

  // News
  'news_center': { ar: 'المركز الإعلامي', en: 'Media Center' },
  'news_subtitle': { ar: 'آخر الأخبار والمراسيم والقرارات الحكومية', en: 'Latest news, decrees, and government decisions' },
  'news_breaking': { ar: 'آخر المستجدات', en: 'Latest Updates' },
  // External Link Modal
  'external_link_warning_title': { ar: 'تنبيه مغادرة الموقع', en: 'Leaving Website Warning' },
  'external_link_warning_desc': { ar: 'أنت على وشك مغادرة موقع وزارة الاقتصاد والصناعة. الوزارة ليست مسؤولة عن محتوى الروابط الخارجية.', en: 'You are about to leave Ministry of Economy and Industry website. The Ministry is not responsible for the content of external links.' },
  'external_link_stay': { ar: 'البقاء في الموقع', en: 'Stay Here' },
  'external_link_continue': { ar: 'متابعة', en: 'Continue' },
  'read_more': { ar: 'اقرأ المزيد', en: 'Read More' },
  'view_archive': { ar: 'عرض الأرشيف', en: 'View Archive' },

  // Footer
  'quick_links': { ar: 'روابط سريعة', en: 'Quick Links' },
  'organizational_structure': { ar: 'الهيكل التنظيمي', en: 'Organizational Structure' },
  'org_general_administrations': { ar: 'الإدارات العامة', en: 'General Administrations' },
  'org_central_directorates': { ar: 'المديريات المركزية', en: 'Central Directorates' },
  'org_affiliated_bodies': { ar: 'الهيئات والمؤسسات التابعة', en: 'Affiliated Bodies & Institutions' },
  'org_sub_directorates_count': { ar: 'مديرية فرعية', en: 'sub-directorates' },
  'org_no_sub_directorates': { ar: 'لا توجد مديريات فرعية', en: 'No sub-directorates' },
  'org_view_department': { ar: 'عرض الإدارة', en: 'View Department' },
  'org_expand': { ar: 'عرض التفاصيل', en: 'Expand' },
  'org_collapse': { ar: 'إخفاء التفاصيل', en: 'Collapse' },
  'contact_us': { ar: 'اتصل بنا', en: 'Contact Us' },
  'accessibility': { ar: 'إمكانية الوصول', en: 'Accessibility' },
  'about_portal': { ar: 'عن البوابة', en: 'About Portal' },
  'footer_admin_login': { ar: 'دخول المسؤولين', en: 'Admin Login' },
  'accessibility_increase': { ar: 'تكبير الخط', en: 'Increase Font' },
  'accessibility_decrease': { ar: 'تصغير الخط', en: 'Decrease Font' },
  'accessibility_high_contrast': { ar: 'تباين عالٍ', en: 'High Contrast' },
  'open_data': { ar: 'البيانات المفتوحة', en: 'Open Data' },
  'site_map': { ar: 'خريطة الموقع (Site Map)', en: 'Site Map' },
  'contact_center': { ar: 'مركز الاتصال الموحد', en: 'Unified Contact Center' },
  'damascus_address': { ar: 'دمشق - الجمارك مقابل الأمن الجنائي', en: 'Damascus - Customs, opposite Criminal Security' },
  'copyright': { ar: '© 2026 وزارة الاقتصاد والصناعة - جميع الحقوق محفوظة.', en: '© 2026 Ministry of Economy and Industry - All Rights Reserved.' },
  'footer_desc': { ar: 'المصدر الموثوق للمعلومات والخدمات.', en: 'The trusted source for information and services.' },

  // Complaints
  'complaint_portal_title': { ar: 'بوابة الشكاوى الذكية', en: 'Smart Complaints Portal' },

  // General
  'switch_lang': { ar: 'English', en: 'عربي' },

  // Quick Services
  'quick_services_title': { ar: 'الخدمات', en: 'Electronic Services' },
  'quick_services_subtitle': { ar: 'وصول سريع لأهم الخدمات الحكومية', en: 'Quick access to the most important e-government services' },
  'service_industrial_license': { ar: 'ترخيص منشأة صناعية', en: 'Industrial Facility License' },
  'service_import_license': { ar: 'إجازة استيراد', en: 'Import License' },
  'service_export_license': { ar: 'إجازة تصدير', en: 'Export License' },
  'service_sme_financing': { ar: 'تمويل المشاريع الصغيرة', en: 'SME Financing' },
  'service_consumer_complaint': { ar: 'شكوى حماية المستهلك', en: 'Consumer Protection Complaint' },
  'service_company_registration': { ar: 'تسجيل شركة تجارية', en: 'Commercial Company Registration' },
  'access_service': { ar: 'الوصول للخدمة', en: 'Access Service' },

  // Stats & Achievements
  'stats_title': { ar: 'إنجازاتنا بالأرقام', en: 'Our Achievements in Numbers' },
  'stats_achievements_title': { ar: 'إنجازات البوابة بالأرقام', en: 'Portal Achievements In Numbers' },
  'stats_subtitle': { ar: 'نعمل على تطوير الخدمات الحكومية لتحقيق رؤية سوريا الرقمية', en: 'Working to develop government services to achieve Syria digital vision' },
  'stat_total_services': { ar: 'خدمة', en: 'E-Services' },
  'stat_transactions': { ar: 'معاملة منجزة', en: 'Completed Transactions' },
  'stat_complaints_resolved': { ar: 'شكوى محلولة', en: 'Resolved Complaints' },
  'stat_satisfaction': { ar: 'نسبة رضا المستخدمين', en: 'User Satisfaction' },

  // Happiness Indicator
  'happiness_title': { ar: 'كيف كانت تجربتك؟', en: 'How was your experience?' },
  'happiness_subtitle': { ar: 'رأيك يهمنا لتطوير خدماتنا بشكل مستمر', en: 'Your opinion matters for our continuous development' },
  'happiness_thanks': { ar: 'شكراً لتقييمك!', en: 'Thank you for your rating!' },

  // Partners
  'partners_title': { ar: 'الجهات الحكومية الشريكة', en: 'Government Partners' },
  'partners_subtitle': { ar: 'شبكة متكاملة من الوزارات والهيئات الحكومية', en: 'An integrated network of ministries and government agencies' },

  // Navigation (Additional)
  'nav_announcements': { ar: 'الإعلانات', en: 'Announcements' },
  'nav_media_center': { ar: 'المركز الإعلامي', en: 'Media Center' },

  // Complaint Portal
  'complaint_submit_tab': { ar: 'تقديم شكوى جديدة', en: 'Submit New Complaint' },
  'complaint_track_tab': { ar: 'متابعة حالة الشكوى', en: 'Track Complaint' },
  'complaint_form_title': { ar: 'نموذج الشكاوى الموحد', en: 'Unified Complaint Form' },
  'complaint_subtitle': { ar: 'سيتم التعامل مع بياناتك بسرية تامة وتوجيهها للجهة المعنية.', en: 'Your data will be treated with complete confidentiality and directed to the relevant authority.' },
  'complaint_personal_info': { ar: 'بيانات مقدم الشكوى', en: 'Complainant Information' },
  'suggestion_personal_info': { ar: 'بيانات مقدم المقترح', en: 'Applicant Information' },
  'complaint_first_name': { ar: 'الاسم الأول', en: 'First Name' },
  'complaint_last_name': { ar: 'الاسم الأخير', en: 'Last Name' },
  'complaint_father_name': { ar: 'اسم الأب', en: 'Father Name' },
  'complaint_national_id': { ar: 'الرقم الوطني', en: 'National ID' },
  'complaint_dob': { ar: 'تاريخ الميلاد', en: 'Date of Birth' },
  'complaint_details': { ar: 'تفاصيل الشكوى', en: 'Complaint Details' },
  'complaint_phone': { ar: 'رقم الهاتف', en: 'Phone Number' },
  'complaint_email': { ar: 'البريد الإلكتروني', en: 'Email Address' },
  'complaint_directorate': { ar: 'الجهة (اختياري)', en: 'Directorate (Optional)' },
  'complaint_entity': { ar: 'الجهة المعنية', en: 'Target Entity' },
  'complaint_select_entity': { ar: '-- اختر الجهة المعنية --', en: '-- Select Entity --' },
  'complaint_submit': { ar: 'إرسال الشكوى', en: 'Submit Complaint' },
  'complaint_success': { ar: 'تم استلام شكواك بنجاح', en: 'Complaint Received Successfully' },
  'complaint_success_desc': { ar: 'يرجى الاحتفاظ برقم تتبع الشكوى أدناه لمتابعة حالة الشكوى. تم إرسال رسالة تأكيد لرقم هاتفك.', en: 'Please keep the tracking number below to track your complaint. A confirmation message has been sent to your phone.' },
  'complaint_ticket_number': { ar: 'رقم تتبع الشكوى', en: 'Tracking Number' },
  'complaint_track_now': { ar: 'متابعة الشكوى الآن', en: 'Track Complaint Now' },
  'complaint_track_title': { ar: 'متابعة الشكاوى', en: 'Track Complaints' },
  'complaint_track_subtitle': { ar: 'أدخل رقم تتبع الشكوى للاستعلام عن آخر المستجدات.', en: 'Enter the tracking number to inquire about the latest updates.' },
  'complaint_track_identified': { ar: 'تتبع بالهوية', en: 'Track with ID' },
  'complaint_track_anonymous': { ar: 'تتبع مجهول', en: 'Anonymous Track' },
  'complaint_track_identified_desc': { ar: 'أدخل رقم تتبع الشكوى والرقم الوطني للتحقق', en: 'Enter tracking number and national ID to verify' },
  'complaint_track_anonymous_desc': { ar: 'أدخل رقم تتبع الشكوى فقط لمتابعة الشكوى المجهولة', en: 'Enter only the tracking number to track your anonymous complaint' },
  'complaint_ticket_label': { ar: 'رقم تتبع الشكوى', en: 'Tracking Number' },
  'complaint_ticket_placeholder': { ar: 'مثال: CMP-20260222-XXXXX', en: 'Example: CMP-20260222-XXXXX' },
  'complaint_national_id_verify': { ar: 'الرقم الوطني (للتحقق)', en: 'National ID (for verification)' },
  'complaint_national_id_placeholder': { ar: 'الرقم الوطني', en: 'National ID' },
  'complaint_search': { ar: 'استعلام', en: 'Search' },
  'complaint_not_found': { ar: 'لم يتم العثور على شكوى بهذا الرقم.', en: 'No complaint found with this tracking number.' },
  'complaint_national_id_invalid': { ar: 'الرقم الوطني يجب أن يتكون من 11 رقماً.', en: 'National ID must be exactly 11 digits.' },
  'complaint_national_id_mismatch': { ar: 'الرقم الوطني لا يتطابق مع الشكوى المسجلة.', en: 'National ID does not match the registered complaint.' },
  'complaint_error': { ar: 'حدث خطأ أثناء الاتصال بالنظام.', en: 'Error connecting to the system.' },
  'complaint_status_new': { ar: 'جديد', en: 'New' },
  'complaint_status_in_progress': { ar: 'قيد المعالجة', en: 'In Progress' },
  'complaint_status_resolved': { ar: 'تم الحل', en: 'Resolved' },
  'complaint_status_rejected': { ar: 'مرفوض', en: 'Rejected' },
  'complaint_last_update': { ar: 'آخر تحديث', en: 'Last Update' },
  'complaint_responses': { ar: 'الردود والتحديثات', en: 'Responses & Updates' },
  'complaint_responses_subtitle': { ar: 'فريق الدعم', en: 'Support Team' },
  'complaint_ocr_upload': { ar: 'أرفق صورة للشكوى المكتوبة (OCR)', en: 'Attach complaint image (OCR)' },
  'complaint_ocr_desc': { ar: 'سيتم استخراج النص تلقائياً من الصورة', en: 'Text will be extracted automatically from the image' },
  'complaint_processing': { ar: 'جاري المعالجة...', en: 'Processing...' },
  'complaint_ticket_prefix': { ar: 'رقم التتبع #', en: 'Tracking #' },
  'complaint_extracted': { ar: 'تم الاستخراج', en: 'Extracted' },
  'complaint_ai_analyze': { ar: 'تحليل ذكي', en: 'AI Analysis' },
  'complaint_analyzing': { ar: 'جاري التحليل...', en: 'Analyzing...' },
  'complaint_ai_result': { ar: 'نتيجة التحليل الذكي', en: 'AI Analysis Result' },
  'complaint_priority': { ar: 'الأولوية', en: 'Priority' },
  'complaint_category_ai': { ar: 'التصنيف', en: 'Category' },
  'complaint_select_directorate': { ar: '-- اختر الجهة --', en: '-- Select Directorate --' },
  'complaint_sending': { ar: 'جاري الإرسال...', en: 'Sending...' },
  'complaint_placeholder': { ar: 'اشرح المشكلة بالتفصيل أو قم برفع صورة المستند...', en: 'Explain the problem in detail or upload a document image...' },
  'complaint_required': { ar: 'مطلوب', en: 'Required' },
  'complaint_national_id_hint': { ar: '11 خانة', en: '11 digits' },

  // Complaint OTP
  'complaint_otp_title': { ar: 'التحقق من الهوية', en: 'Identity Verification' },
  'complaint_otp_desc': { ar: 'لضمان أمان شكواك، يرجى التحقق من هويتك عبر رمز يُرسل إلى هاتفك المحمول', en: 'To ensure the security of your complaint, please verify your identity via a code sent to your mobile phone' },
  'complaint_otp_fill_fields': { ar: 'يرجى إدخال رقم الهاتف والرقم الوطني أولاً', en: 'Please enter your phone number and national ID first' },
  'complaint_otp_sent': { ar: 'تم إرسال رمز التحقق بنجاح', en: 'Verification code sent successfully' },
  'complaint_otp_send_failed': { ar: 'فشل إرسال رمز التحقق', en: 'Failed to send verification code' },
  'complaint_otp_verified': { ar: 'تم التحقق بنجاح', en: 'Verified successfully' },
  'complaint_otp_verify_failed': { ar: 'فشل التحقق من الرمز', en: 'Code verification failed' },
  'complaint_otp_enter_code': { ar: 'أدخل رمز التحقق المرسل إلى هاتفك', en: 'Enter the verification code sent to your phone' },
  'complaint_otp_verify': { ar: 'تحقق', en: 'Verify' },
  'complaint_otp_resend': { ar: 'إعادة إرسال الرمز', en: 'Resend Code' },
  'complaint_otp_send': { ar: 'إرسال رمز التحقق', en: 'Send Verification Code' },
  'complaint_otp_identity_verified': { ar: 'تم التحقق من هويتك بنجاح', en: 'Your identity has been verified successfully' },
  'complaint_prev_ticket_placeholder': { ar: 'مثال: GOV-12345', en: 'Example: GOV-12345' },

  // News Section (Additional)
  'news_archive_title': { ar: 'المحتوى الاعلامي', en: 'Media Archive' },
  'news_archive_desc': { ar: 'تصفح كافة الأخبار والقرارات والتقارير الصحفية الصادرة.', en: 'Browse all news, decisions, and press releases.' },
  'news_filter_all': { ar: 'الكل', en: 'All' },
  'news_filter_politics': { ar: 'سياسة', en: 'Politics' },
  'news_filter_economy': { ar: 'اقتصاد', en: 'Economy' },
  'news_filter_services': { ar: 'خدمات', en: 'Services' },
  'news_filter_decrees': { ar: 'مراسيم', en: 'Decrees' },
  'news_load_more': { ar: 'تحميل المزيد', en: 'Load More' },
  'news_read_details': { ar: 'اقرأ التفاصيل', en: 'Read Details' },
  'news_no_results': { ar: 'لا توجد نتائج', en: 'No results' },
  'news_show_all': { ar: 'عرض الأرشيف الكامل', en: 'View Full Archive' },
  'decrees_title': { ar: 'القوانين والتشريعات', en: 'Laws & Legislation' },
  'decrees_subtitle': { ar: 'البوابة الرسمية للوصول إلى كافة المراسيم التشريعية، القوانين، والقرارات الحكومية الصادرة في الجمهورية العربية السورية.', en: 'The official portal for accessing all legislative decrees, laws, and government decisions issued in the Syrian Arab Republic.' },
  'decrees_search_placeholder': { ar: 'بحث برقم المرسوم، السنة، أو العنوان...', en: 'Search by decree number, year, or title...' },
  'decrees_filter_all': { ar: 'الكل', en: 'All' },
  'decrees_type_legislative': { ar: 'مرسوم تشريعي', en: 'Legislative Decree' },
  'decrees_type_law': { ar: 'قانون', en: 'Law' },
  'decrees_type_presidential': { ar: 'قرار رئاسي', en: 'Presidential Decree' },
  'decrees_type_circular': { ar: 'تعميم', en: 'Circular' },
  'decrees_no_results': { ar: 'لا توجد وثائق مطابقة للبحث', en: 'No matching documents found' },
  'decrees_number_label': { ar: 'رقم', en: 'No.' },
  'decrees_year_label': { ar: 'عام', en: 'Year' },
  'decrees_issue_date': { ar: 'تاريخ الصدور:', en: 'Issue Date:' },
  'decrees_download_pdf': { ar: 'تحميل PDF', en: 'Download PDF' },

  // Chat Bot
  'chat_title': { ar: 'المساعد الحكومي الذكي', en: 'Smart Government Assistant' },
  'chat_online': { ar: 'متصل الآن - يحتفظ بالسياق', en: 'Online - Maintains Context' },
  'chat_welcome': { ar: 'مرحباً بك في البوابة الإلكترونية لوزارة الاقتصاد والصناعة. أنا المساعد الذكي، كيف يمكنني مساعدتك في خدمات الصناعة والتجارة والاقتصاد؟', en: 'Welcome to the Ministry of Economy and Industry E-Portal. I am the smart assistant, how can I help you with industry, trade, and economy services today?' },
  'chat_placeholder': { ar: 'اكتب استفسارك هنا...', en: 'Type your inquiry here...' },
  'chat_attach': { ar: 'إرفاق صورة أو مستند', en: 'Attach image or document' },
  'chat_attach_title': { ar: 'إرفاق صورة أو مستند', en: 'Attach image or document' },
  'chat_ready': { ar: 'جاهز للإرسال (OCR)', en: 'Ready to send (OCR)' },
  'chat_error': { ar: 'عذراً، حدث خطأ في الاتصال بالخدمة. يرجى المحاولة مرة أخرى.', en: 'Sorry, an error occurred connecting to the service. Please try again.' },
  'chat_send': { ar: 'إرسال', en: 'Send' },
  'chat_clear': { ar: 'مسح المحادثة والبدء من جديد', en: 'Clear chat and start over' },
  'chat_clear_title': { ar: 'مسح المحادثة والبدء من جديد', en: 'Clear chat and start over' },
  'chat_disclaimer': { ar: 'هذا النظام مدعوم بالذكاء الاصطناعي ويتذكر محادثاتك السابقة.', en: 'This system is AI-powered and remembers your previous conversations.' },
  'chat_file_large': { ar: 'حجم الملف كبير جداً. يرجى اختيار ملف أقل من 5 ميغابايت.', en: 'File size too large. Please select a file less than 5MB.' },
  'chat_floating_label': { ar: 'المساعد الذكي', en: 'Smart Assistant' },
  'chat_analyze_image': { ar: 'قم بتحليل النص المستخرج من الصورة', en: 'Analyze the text extracted from the image' },
  'chat_analyze_file': { ar: 'قم بتحليل هذا الملف المرفق.', en: 'Analyze this attached file.' },
  'chat_attachment_label': { ar: ' [مرفق: ', en: ' [Attachment: ' },

  // Contact Section
  'contact_title': { ar: 'تواصل معنا', en: 'Contact Us' },
  'contact_subtitle': { ar: 'نحن هنا لخدمتك. يمكنك التواصل معنا عبر النموذج الإلكتروني الموحد أو عبر قنوات الاتصال الرسمية.', en: 'We are here to serve you. You can contact us via the unified electronic form or through official communication channels.' },
  'contact_info': { ar: 'معلومات الاتصال', en: 'Contact Information' },
  'contact_info_desc': { ar: 'للاستفسارات العاجلة، يرجى الاتصال بمركز خدمة المواطن الموحد. فريقنا جاهز للرد على استفساراتكم على مدار الساعة.', en: 'For urgent inquiries, please contact the unified citizen service center. Our team is ready to respond to your inquiries 24/7.' },
  'contact_hotline': { ar: 'الخط الساخن الموحد', en: 'Unified Hotline' },
  'contact_email_label': { ar: 'البريد الإلكتروني', en: 'Email Address' },
  'contact_headquarters': { ar: 'المقر الرئيسي', en: 'Headquarters' },
  'contact_hours': { ar: 'ساعات العمل', en: 'Working Hours' },
  'contact_hours_value': { ar: 'الأحد - الخميس: 8:00 ص - 3:30 م', en: 'Sunday - Thursday: 8:00 AM - 3:30 PM' },
  'contact_form_title': { ar: 'نموذج المراسلة الإلكتروني', en: 'Electronic Messaging Form' },
  'contact_success_title': { ar: 'تم إرسال رسالتك بنجاح', en: 'Message Sent Successfully' },
  'contact_success_desc': { ar: 'سيتم الرد على استفسارك خلال 24 ساعة عمل.', en: 'Your inquiry will be responded to within 24 business hours.' },
  'contact_full_name': { ar: 'الاسم الكامل', en: 'Full Name' },
  'contact_email': { ar: 'البريد الإلكتروني', en: 'Email Address' },
  'contact_subject': { ar: 'عنوان الرسالة', en: 'Message Subject' },
  'contact_directorate': { ar: 'الجهة المختصة', en: 'Relevant Directorate' },
  'contact_select_directorate': { ar: '-- اختر الجهة --', en: '-- Select Directorate --' },
  'contact_general': { ar: 'الاستعلامات العامة', en: 'General Inquiries' },
  'contact_complaints': { ar: 'مكتب الشكاوى', en: 'Complaints Office' },
  'contact_media': { ar: 'المكتب الإعلامي', en: 'Media Office' },
  'contact_message': { ar: 'نص الرسالة', en: 'Message Text' },
  'contact_send': { ar: 'إرسال الرسالة', en: 'Send Message' },
  'contact_sending': { ar: 'جاري الإرسال...', en: 'Sending...' },
  'contact_email_placeholder': { ar: 'example@email.com', en: 'example@email.com' },
  'contact_name_placeholder': { ar: 'الاسم الكامل', en: 'Full Name' },
  'contact_subject_placeholder': { ar: 'عنوان الرسالة', en: 'Message Subject' },
  'contact_message_placeholder': { ar: 'اكتب رسالتك هنا...', en: 'Write your message here...' },

  // FAQ Section
  'faq_center': { ar: 'مركز المساعدة', en: 'Help Center' },
  'faq_title': { ar: 'الأسئلة الشائعة', en: 'Frequently Asked Questions' },
  'faq_subtitle': { ar: 'إجابات على أكثر الاستفسارات شيوعاً حول الخدمات والبوابة.', en: 'Answers to the most common inquiries about services and the portal.' },
  'faq_q1': { ar: 'كيف يمكنني إنشاء حساب جديد على بوابة المواطن؟', en: 'How can I create a new account on the citizen portal?' },
  'faq_a1': { ar: 'يمكنك إنشاء حساب جديد بالضغط على زر "تسجيل الدخول" في أعلى الصفحة واختيار "إنشاء حساب". ستحتاج إلى رقمك الوطني ورقم هاتف فعال.', en: 'You can create a new account by clicking the "Sign In" button at the top of the page and selecting "Create Account". You will need your national ID and an active phone number.' },
  'faq_q2': { ar: 'هل يمكنني تقديم شكوى دون الكشف عن هويتي؟', en: 'Can I submit a complaint without revealing my identity?' },
  'faq_a2': { ar: 'نعم، النظام يتيح تقديم الشكاوى بشكل سري تام. لا يمكن لأي جهة معرفة هوية مقدم الشكوى المجهول، وسيتم معالجة شكواك بنفس الاهتمام والجدية ولن يطلع عليه أحد.', en: 'Yes, the system allows fully anonymous complaint submission. No entity can identify the anonymous complainant, your complaint will be processed with the same attention and seriousness, and no one will have access to your identity.' },
  'faq_q3': { ar: 'كم تستغرق معالجة طلبات الخدمات؟', en: 'How long does it take to process e-service requests?' },
  'faq_a3': { ar: 'تختلف المدة حسب نوع الخدمة، ولكن معظم الخدمات الفورية (مثل استخراج البيانات) تتم خلال دقائق. المعاملات التي تتطلب تدقيقاً قد تستغرق من 1 إلى 3 أيام عمل.', en: 'The duration varies depending on the service type, but most instant e-services (such as data extraction) are completed within minutes. Transactions requiring verification may take 1 to 3 business days.' },
  'faq_q4': { ar: 'ما هي الوثائق المطلوبة للحصول على ترخيص منشأة صناعية؟', en: 'What documents are required for an industrial facility license?' },
  'faq_a4': { ar: 'يتطلب الحصول على ترخيص منشأة صناعية: دراسة جدوى اقتصادية، مخططات الموقع، الوثائق القانونية للشركة، والموافقات البيئية. يمكنك إتمام العملية عبر الإدارة العامة للصناعة.', en: 'Industrial facility license requires: economic feasibility study, site plans, company legal documents, and environmental approvals. You can complete the process through the General Administration for Industry.' },
  'faq_q5': { ar: 'كيف يمكنني دفع الرسوم الحكومية؟', en: 'How can I pay government fees?' },
  'faq_a5': { ar: 'تدعم البوابة الدفع الإلكتروني عبر المصارف العامة والخاصة المرتبطة بشبكة المدفوعات الوطنية، بالإضافة إلى الدفع عبر شركات الهاتف المحمول.', en: 'The portal supports electronic payment through public and private banks connected to the national payment network, in addition to payment through mobile phone companies.' },
  'field_valid': { ar: '✅ الحقل صالح', en: '✅ Field is valid' },

  // About Page
  'about_title': { ar: 'عن البوابة الإلكترونية', en: 'About the E-Portal' },
  'about_subtitle': { ar: 'المنصة الوطنية الموحدة للخدمات الحكومية في الجمهورية العربية السورية. رؤية طموحة لمستقبل رقمي يخدم المواطن ويعزز الشفافية.', en: 'The unified national platform for government services in the Syrian Arab Republic. An ambitious vision for a digital future that serves citizens and enhances transparency.' },
  'about_mission': { ar: 'رسالتنا', en: 'Our Mission' },
  'about_mission_desc': { ar: 'تقديم خدمات حكومية ذكية، متكاملة، وآمنة، تتيح للمواطنين إتمام معاملاتهم بسهولة ويسر من أي مكان وفي أي وقت، مما يساهم في رفع كفاءة العمل الحكومي وتقليل البيروقراطية.', en: 'Providing smart, integrated, and secure government services that enable citizens to complete their transactions easily and conveniently from anywhere and at any time, contributing to improving government efficiency and reducing bureaucracy.' },
  'about_vision': { ar: 'رؤيتنا', en: 'Our Vision' },
  'about_vision_desc': { ar: 'حكومة بلا ورق بحلول عام 2030، تعتمد على البيانات والتقنيات الحديثة لصنع القرار، وتضع رضا المواطن في قلب أولوياتها من خلال تجربة مستخدم سلسة وشفافة.', en: 'A paperless government by 2030, relying on data and modern technologies for decision-making, placing citizen satisfaction at the heart of its priorities through a seamless and transparent user experience.' },
  'requested_services_title': { ar: 'الخدمات الأكثر طلباً', en: 'Most Requested Services' },
  'requested_services_subtitle': { ar: 'الوصول السريع إلى حزمة الخدمات الأكثر أهمية', en: 'Quick access to the most important e-government services' },
  'view_all_services': { ar: 'عرض كافة الخدمات', en: 'View All Services' },
  's_passport': { ar: 'الجواز الإلكتروني', en: 'E-Passport' },
  's_traffic': { ar: 'مخالفات المرور', en: 'Traffic Fines' },
  's_electricity': { ar: 'فواتير الكهرباء', en: 'Electricity Bills' },
  's_exams': { ar: 'النتائج الامتحانية', en: 'Exam Results' },
  's_finance': { ar: 'براءة الذمة', en: 'Financial Clearance' },
  's_property': { ar: 'البيان العقاري', en: 'Property Statement' },
  'about_pillars': { ar: 'ركائزنا الاستراتيجية', en: 'Our Strategic Pillars' },
  'about_security': { ar: 'الأمان والخصوصية', en: 'Security & Privacy' },
  'about_security_desc': { ar: 'حماية بيانات المواطنين وفق أعلى المعايير العالمية.', en: 'Protecting citizens data according to the highest global standards.' },
  'about_inclusivity': { ar: 'الشمولية', en: 'Inclusivity' },
  'about_inclusivity_desc': { ar: 'خدمات متاحة لجميع فئات المجتمع بما في ذلك ذوي الاحتياجات الخاصة.', en: 'Services available to all segments of society including people with special needs.' },
  'about_digital': { ar: 'التحول الرقمي', en: 'Digital Transformation' },
  'about_digital_desc': { ar: 'أتمتة شاملة للإجراءات وربط المؤسسات الحكومية.', en: 'Comprehensive automation of procedures and linking government institutions.' },
  'about_efficiency': { ar: 'الكفاءة والسرعة', en: 'Efficiency & Speed' },
  'about_efficiency_desc': { ar: 'تقليص زمن إنجاز المعاملات ورفع جودة الأداء.', en: 'Reducing transaction completion time and improving performance quality.' },
  'about_users': { ar: 'مستخدم نشط', en: 'Active Users' },
  'about_services_count': { ar: 'خدمة', en: 'E-Services' },
  'about_satisfaction': { ar: 'نسبة الرضا', en: 'Satisfaction Rate' },
  'about_support': { ar: 'دعم فني', en: 'Technical Support' },

  // Open Data
  'open_data_title': { ar: 'منصة البيانات المفتوحة', en: 'Open Data Platform' },
  'open_data_subtitle': { ar: 'تعزيزاً للشفافية والابتكار، تتيح الحكومة الوصول إلى مجموعة واسعة من البيانات الحكومية القابلة للمعالجة وإعادة الاستخدام مجاناً.', en: 'To promote transparency and innovation, the government provides access to a wide range of government data that can be processed and reused for free.' },
  'open_data_search': { ar: 'بحث عن مجموعة بيانات...', en: 'Search for dataset...' },
  'open_data_filter': { ar: 'تصفية', en: 'Filter' },
  'open_data_size': { ar: 'الحجم', en: 'Size' },
  'open_data_updated': { ar: 'آخر تحديث', en: 'Last Updated' },
  'open_data_format': { ar: 'الصيغة', en: 'Format' },
  'open_data_download': { ar: 'تحميل البيانات', en: 'Download Data' },
  'announcements_latest': { ar: 'آخر التحديثات', en: 'Latest Updates' },
  'announcements_title': { ar: 'الإعلانات', en: 'Announcements' },
  'announcements_subtitle': { ar: 'تابع أحدث الإعلانات والمناقصات والفرص الحكومية', en: 'Stay updated with the latest announcements, tenders, and government opportunities' },
  'announcements_type_urgent': { ar: 'عاجل', en: 'Urgent' },
  'announcements_type_important': { ar: 'هام', en: 'Important' },
  'announcements_type_general': { ar: 'إعلان', en: 'Announcement' },
  'announcements_view_all': { ar: 'عرض جميع الإعلانات', en: 'View All Announcements' },
  'announcements_read_more': { ar: 'قراءة المزيد', en: 'Read More' },
  'open_data_education': { ar: 'التعليم', en: 'Education' },
  'open_data_health': { ar: 'الصحة', en: 'Health' },
  'open_data_finance': { ar: 'المالية', en: 'Finance' },
  'open_data_energy': { ar: 'الطاقة', en: 'Energy' },
  'open_data_tourism': { ar: 'السياحة', en: 'Tourism' },
  'open_data_environment': { ar: 'البيئة', en: 'Environment' },
  'open_data_daily': { ar: 'يومياً', en: 'Daily' },
  'open_data_photos': { ar: 'صور', en: 'photos' },

  // Authentication

  // Authentication
  'auth_login_title': { ar: 'تسجيل الدخول', en: 'Sign In' },
  'auth_login_subtitle': { ar: 'سجل دخولك للوصول إلى خدماتك الحكومية', en: 'Sign in to access your government services' },
  'auth_register_title': { ar: 'إنشاء حساب جديد', en: 'Create Account' },
  'auth_register_subtitle': { ar: 'سجل الآن للوصول إلى جميع الخدمات الحكومية', en: 'Register now to access all government services' },
  'auth_email': { ar: 'البريد الإلكتروني', en: 'Email Address' },
  'auth_phone': { ar: 'رقم الهاتف', en: 'Phone Number' },
  'auth_national_id': { ar: 'الرقم الوطني', en: 'National ID' },
  'auth_password': { ar: 'كلمة المرور', en: 'Password' },
  'auth_remember': { ar: 'تذكرني', en: 'Remember me' },
  'auth_forgot_password': { ar: 'نسيت كلمة المرور؟', en: 'Forgot password?' },
  'auth_sign_in_btn': { ar: 'تسجيل الدخول', en: 'Sign In' },
  'auth_no_account': { ar: 'ليس لديك حساب؟', en: "Don't have an account?" },
  'auth_create_account': { ar: 'إنشاء حساب جديد', en: 'Create account' },
  'auth_back_home': { ar: 'العودة للرئيسية', en: 'Back to Home' },
  'auth_back_login': { ar: 'العودة لتسجيل الدخول', en: 'Back to Login' },
  'auth_secure': { ar: 'اتصال آمن ومشفر', en: 'Secure encrypted connection' },
  'auth_verify': { ar: 'تحقق من الهوية', en: 'Identity verification' },
  'auth_protect': { ar: 'حماية بياناتك الشخصية', en: 'Personal data protection' },
  'auth_ministry_name': { ar: 'وزارة الاقتصاد والصناعة', en: 'Ministry of Economy and Industry' },
  'auth_enter_email': { ar: 'أدخل بريدك الإلكتروني', en: 'Enter your email' },
  'auth_enter_phone': { ar: 'أدخل رقم الهاتف', en: 'Enter phone number' },
  'auth_enter_national_id': { ar: 'أدخل الرقم الوطني', en: 'Enter your national ID' },
  'auth_enter_password': { ar: 'أدخل كلمة المرور', en: 'Enter your password' },
  'auth_ssl_secure': { ar: 'اتصال آمن ومشفر بتقنية SSL', en: 'Secure SSL encrypted connection' },
  'auth_method_email': { ar: 'بريد', en: 'Email' },
  'auth_method_phone': { ar: 'هاتف', en: 'Phone' },
  'auth_method_id': { ar: 'وطني', en: 'ID' },

  // Registration Steps
  'reg_step_personal': { ar: 'المعلومات الشخصية', en: 'Personal Info' },
  'reg_step_contact': { ar: 'معلومات الاتصال', en: 'Contact Info' },
  'reg_step_password': { ar: 'كلمة المرور', en: 'Password' },
  'reg_full_name': { ar: 'الاسم الكامل', en: 'Full Name' },
  'reg_full_name_placeholder': { ar: 'الاسم الثلاثي', en: 'Full name' },
  'reg_birth_date': { ar: 'تاريخ الميلاد', en: 'Birth Date' },
  'reg_governorate': { ar: 'المحافظة', en: 'Governorate' },
  'reg_select_governorate': { ar: 'اختر المحافظة', en: 'Select governorate' },
  'reg_phone_placeholder': { ar: 'أدخل رقم الهاتف', en: 'Enter phone number' },
  'reg_verification': { ar: 'سيتم إرسال رمز التحقق إلى بريدك الإلكتروني للتأكد من صحة البيانات.', en: 'A verification code will be sent to your email to verify your information.' },
  'reg_new_password': { ar: 'كلمة المرور الجديدة', en: 'New Password' },
  'reg_password_placeholder': { ar: 'أدخل كلمة مرور قوية', en: 'Enter a strong password' },
  'reg_confirm_password': { ar: 'تأكيد كلمة المرور', en: 'Confirm Password' },
  'reg_reenter_password': { ar: 'أعد إدخال كلمة المرور', en: 'Re-enter password' },
  'reg_password_requirements': { ar: 'متطلبات كلمة المرور:', en: 'Password requirements:' },
  'reg_password_length': { ar: '8 أحرف على الأقل', en: 'At least 8 characters' },
  'reg_password_uppercase': { ar: 'حرف كبير واحد على الأقل', en: 'At least one uppercase letter' },
  'reg_password_number': { ar: 'رقم واحد على الأقل', en: 'At least one number' },
  'reg_password_lowercase': { ar: 'حرف صغير واحد على الأقل', en: 'At least one lowercase letter' },
  'reg_password_special': { ar: 'رمز خاص واحد على الأقل (!@#$%^&*)', en: 'At least one special character (!@#$%^&*)' },
  'validation_password_weak': { ar: 'كلمة المرور لا تستوفي جميع المتطلبات', en: 'Password does not meet all requirements' },
  'reg_agree_terms': { ar: 'أوافق على شروط الاستخدام وسياسة الخصوصية', en: 'I agree to Terms of Service and Privacy Policy' },
  'reg_previous': { ar: 'السابق', en: 'Previous' },
  'reg_next': { ar: 'التالي', en: 'Next' },
  'reg_create': { ar: 'إنشاء الحساب', en: 'Create Account' },
  'reg_whatsapp_enable': { ar: 'تفعيل الواتساب للتنبيهات', en: 'Enable WhatsApp Notifications' },
  'reg_whatsapp_desc': { ar: 'سوف يصلك رمز التحقق عبر الواتساب بدلاً من الرسائل النصية', en: 'You will receive verification codes via WhatsApp instead of SMS' },
  'reg_protected': { ar: 'بياناتك محمية ومشفرة', en: 'Your data is protected & encrypted' },
  'reg_already_account': { ar: 'لديك حساب بالفعل؟', en: 'Already have an account?' },
  'reg_back_home': { ar: '← العودة للصفحة الرئيسية', en: '← Back to Home' },

  // Forgot Password
  'forgot_title': { ar: 'نسيت كلمة المرور؟', en: 'Forgot Password?' },
  'forgot_subtitle': { ar: 'أدخل بريدك الإلكتروني لإرسال رابط إعادة تعيين كلمة المرور', en: 'Enter your email to receive a password reset link' },
  'forgot_email_placeholder': { ar: 'example@domain.com', en: 'example@domain.com' },
  'forgot_send_link': { ar: 'إرسال الرابط', en: 'Send Link' },
  'forgot_sent_title': { ar: 'تم الإرسال', en: 'Email Sent' },
  'forgot_sent_desc': { ar: 'تم إرسال تعليمات إعادة تعيين كلمة المرور إلى بريدك الإلكتروني.', en: 'Password reset instructions have been sent to your email.' },
  'forgot_back_login': { ar: 'العودة لتسجيل الدخول', en: 'Back to Login' },

  // Reset Password
  'reset_title': { ar: 'إعادة تعيين كلمة المرور', en: 'Reset Password' },
  'reset_subtitle': { ar: 'أدخل كلمة المرور الجديدة لحسابك', en: 'Enter a new password for your account' },
  'reset_new_password': { ar: 'كلمة المرور الجديدة', en: 'New Password' },
  'reset_confirm_password': { ar: 'تأكيد كلمة المرور', en: 'Confirm Password' },
  'reset_save': { ar: 'حفظ التغييرات', en: 'Save Changes' },
  'reset_success_title': { ar: 'تم تغيير كلمة المرور', en: 'Password Changed' },
  'reset_success_desc': { ar: 'تم تحديث كلمة المرور بنجاح. يمكنك الآن تسجيل الدخول.', en: 'Your password has been successfully updated. You can now login.' },
  'reset_mismatch': { ar: 'كلمات المرور غير متطابقة', en: 'Passwords do not match' },
  'reset_cancel': { ar: 'إلغاء', en: 'Cancel' },
  'reset_signin': { ar: 'تسجيل الدخول', en: 'Sign In' },

  // Services Guide
  'services_guide_title': { ar: 'دليل الخدمات الحكومية', en: 'Government Services Guide' },
  'services_guide_subtitle': { ar: 'تصفح جميع الخدمات الحكومية والتقليدية المتاحة للمواطنين', en: 'Browse all electronic and traditional government services available to citizens' },
  'services_search': { ar: 'ابحث عن خدمة...', en: 'Search for a service...' },
  'services_all_agencies': { ar: 'جميع الجهات', en: 'All Agencies' },
  'services_filter_all': { ar: 'الكل', en: 'All' },
  'services_digital': { ar: 'إلكترونية', en: 'Digital' },
  'services_in_person': { ar: 'حضورية', en: 'In-Person' },
  'services_available': { ar: 'خدمة متاحة', en: 'services available' },
  'services_instant': { ar: 'فوري', en: 'Instant' },
  'services_apply': { ar: 'تقديم الطلب', en: 'Apply' },
  'services_no_results': { ar: 'لا توجد نتائج', en: 'No Results Found' },
  'services_try_change': { ar: 'جرب تغيير معايير البحث أو الفلترة', en: 'Try changing your search or filter criteria' },

  // Media Center
  'media_center_title': { ar: 'المركز الإعلامي', en: 'Media Center' },
  'media_center_subtitle': { ar: 'مكتبة الفيديو والصور والإنفوجرافيك الرسمية من وزارة الاقتصاد والصناعة', en: 'Official video, photo, and infographic library from Ministry of Economy and Industry' },
  'media_filter_all': { ar: 'الكل', en: 'All' },
  'media_filter_video': { ar: 'فيديو', en: 'Videos' },
  'media_filter_photo': { ar: 'صور', en: 'Photos' },
  'media_filter_infographic': { ar: 'إنفوجرافيك', en: 'Infographics' },
  'media_items': { ar: 'عنصر', en: 'items' },
  'media_view': { ar: 'مشاهدة', en: 'View' },
  'media_share': { ar: 'مشاركة', en: 'Share' },
  'media_download': { ar: 'تحميل', en: 'Download' },
  'media_no_items': { ar: 'لا توجد عناصر', en: 'No Items Found' },
  'media_no_content': { ar: 'لا يوجد محتوى في هذه الفئة حالياً', en: 'No content in this category currently' },
  'media_duration': { ar: 'مدة', en: 'Duration' },
  'media_photos_count': { ar: 'صور', en: 'photos' },
  'media_play': { ar: 'تشغيل', en: 'Play' },
  'media_expand': { ar: 'توسيع', en: 'Expand' },
  'media_back_to_album': { ar: 'العودة للألبوم', en: 'Back to Album' },
  'media_download_all': { ar: 'تحميل الألبوم كاملاً', en: 'Download All Photos' },
  'media_downloading': { ar: 'جاري التحميل', en: 'Downloading' },
  'media_photo_label': { ar: 'صورة', en: 'Photo' },
  'media_no_album_photos': { ar: 'لا توجد صور في هذا الألبوم', en: 'No photos in this album' },
  'media_browser_no_video': { ar: 'المتصفح لا يدعم تشغيل الفيديو.', en: 'Your browser does not support the video tag.' },
  'media_loading': { ar: 'جار التحميل...', en: 'Loading...' },
  // News Page
  'news_page_title': { ar: 'المحتوى الإعلامي', en: 'Media Content' },
  'news_page_subtitle': { ar: 'تصفح كافة الأخبار والقرارات والتقارير الصحفية الصادرة.', en: 'Browse all news, decisions, and press reports.' },
  'news_organized_view': { ar: 'عرض منظم', en: 'Organized View' },
  'news_all': { ar: 'جميع الأخبار', en: 'All News' },
  'news_central_admin': { ar: 'أخبار الإدارة المركزية', en: 'Central Admin News' },
  'news_featured': { ar: 'الخبر الرئيسي', en: 'Featured News' },
  'news_view_all': { ar: 'عرض جميع الأخبار', en: 'View All News' },
  'news_no_results_desc': { ar: 'لم يتم العثور على أخبار مطابقة.', en: 'No news found matching your criteria.' },
  'news_article_count': { ar: 'خبر', en: 'articles' },
  'news_read_more': { ar: 'اقرأ التفاصيل', en: 'Read More' },
  'news_view_all_btn': { ar: 'عرض الكل', en: 'View All' },
  'news_back_to_center': { ar: 'العودة لمركز الأخبار', en: 'Back to News Center' },
  'news_not_found': { ar: 'عفواً، الخبر غير موجود', en: 'Article Not Found' },
  'news_not_found_desc': { ar: 'قد يكون هذا الخبر قد تم نقله أو حذفه.', en: 'This article might have been moved or deleted.' },
  'news_ai_summary': { ar: 'ملخص ذكي', en: 'AI Summary' },
  'news_ai_label': { ar: 'ملخص AI', en: 'AI' },
  'news_faq_title': { ar: 'الأسئلة الشائعة', en: 'Frequently Asked Questions' },
  'news_faq_q1': { ar: 'كيف أبقى على اطلاع بآخر الأخبار؟', en: 'How do I stay updated with latest news?' },
  'news_faq_a1': { ar: 'يمكنك متابعة أحدث الأخبار من خلال هذه الصفحة أو الاشتراك في النشرة البريدية للوزارة.', en: 'You can follow the latest news through this page or subscribe to the ministry newsletter.' },
  'news_faq_q2': { ar: 'هل يمكنني تصفية الأخبار حسب المديرية؟', en: 'Can I filter news by directorate?' },
  'news_faq_a2': { ar: 'نعم، استخدم أزرار الفلترة أعلاه لتصفية الأخبار حسب المديرية أو الفترة الزمنية.', en: 'Yes, use the filter buttons above to filter news by directorate or time period.' },
  'news_faq_q3': { ar: 'ما هو الملخص الذكي؟', en: 'What is AI Summary?' },
  'news_faq_a3': { ar: 'خدمة تعتمد على الذكاء الاصطناعي لتلخيص محتوى الأخبار الطويلة بشكل مختصر ومفيد.', en: 'An AI-powered service that summarizes long news content into a concise and useful format.' },
  'news_faq_view_all': { ar: 'عرض جميع الأسئلة الشائعة ←', en: '→ View all FAQs' },
  'news_no_enough_content': { ar: 'لا يوجد محتوى كافٍ لإنشاء ملخص.', en: 'Not enough content to generate a summary.' },
  'news_ai_unavailable': { ar: 'تعذر إنشاء الملخص الذكي حالياً. هذه نبذة مختصرة من الخبر:', en: 'AI summary is temporarily unavailable. Showing a short article excerpt instead:' },



  // Search Results
  'search_results': { ar: 'نتائج البحث', en: 'Search Results' },
  'search_results_title': { ar: 'نتائج البحث', en: 'Search Results' },
  'search_advanced': { ar: 'بحث متقدم وفلاتر', en: 'Advanced Search & Filters' },
  'search_from': { ar: 'من تاريخ', en: 'From Date' },
  'search_to': { ar: 'إلى تاريخ', en: 'To Date' },
  'search_date_from': { ar: 'من تاريخ', en: 'From Date' },
  'search_date_to': { ar: 'إلى تاريخ', en: 'To Date' },
  'search_entity': { ar: 'الجهة / التصنيف', en: 'Entity / Category' },
  'search_reset': { ar: 'إعادة تعيين', en: 'Reset' },
  'search_tab_all': { ar: 'الكل', en: 'All' },
  'search_tab_news': { ar: 'أخبار', en: 'News' },
  'search_tab_decrees': { ar: 'قوانين وتشريعات', en: 'Laws & Legislation' },
  'search_tab_announcements': { ar: 'إعلانات', en: 'Announcements' },
  'search_section_news': { ar: 'الأخبار', en: 'News' },
  'search_section_decrees': { ar: 'القوانين والتشريعات', en: 'Laws & Legislation' },
  'search_no_results': { ar: 'لا توجد نتائج', en: 'No results found' },
  'search_try_keywords': { ar: 'جرب كلمات بحث مختلفة', en: 'Try different keywords' },
  'search_try_again': { ar: 'جرب تغيير معايير البحث', en: 'Try changing search criteria' },
  'search_no': { ar: 'رقم', en: 'No' },
  'search_number': { ar: 'رقم', en: 'No' },
  'decree_no_label': { ar: 'رقم', en: 'No' },

  // Sitemap
  'sitemap_title': { ar: 'خريطة الموقع', en: 'Site Map' },
  'sitemap_subtitle': { ar: 'استعرض جميع صفحات وأقسام البوابة الإلكترونية للوصول السريع', en: 'Browse all pages and sections of the portal for quick access' },
  'sitemap_back': { ar: 'العودة للرئيسية', en: 'Back to Home' },
  'sitemap_home': { ar: 'الصفحة الرئيسية', en: 'Home' },
  'sitemap_directory': { ar: 'دليل الجهات الحكومية', en: 'Government Directory' },
  'sitemap_services': { ar: 'دليل الخدمات', en: 'Services Guide' },
  'sitemap_decrees': { ar: 'القوانين والتشريعات', en: 'Laws & Legislation' },
  'sitemap_media': { ar: 'المركز الإعلامي', en: 'Media Center' },
  'sitemap_complaints': { ar: 'منظومة الشكاوى', en: 'Complaints System' },
  'sitemap_about': { ar: 'عن البوابة', en: 'About Portal' },
  'sitemap_open_data': { ar: 'البيانات المفتوحة', en: 'Open Data' },
  'sitemap_account': { ar: 'حساب المستخدم', en: 'User Account' },
  'sitemap_sub_pages': { ar: 'صفحة فرعية', en: 'sub-pages' },
  'sitemap_service_categories': { ar: 'فئات الخدمات (14 فئة)', en: 'Service Categories (14)' },
  'sitemap_industry': { ar: 'الإدارة العامة للصناعة', en: 'General Administration for Industry' },
  'sitemap_economy': { ar: 'الإدارة العامة للاقتصاد', en: 'General Administration for Economy' },
  'sitemap_trade': { ar: 'الإدارة العامة للتجارة الداخلية وحماية المستهلك', en: 'General Administration for Internal Trade & Consumer Protection' },
  'sitemap_legislative_decrees': { ar: 'المراسيم التشريعية', en: 'Legislative Decrees' },
  'sitemap_laws': { ar: 'القوانين', en: 'Laws' },
  'sitemap_presidential_decisions': { ar: 'القرارات الرئاسية', en: 'Presidential Decisions' },
  'sitemap_circulars': { ar: 'التعاميم', en: 'Circulars' },
  'sitemap_news': { ar: 'الأخبار', en: 'News' },
  'sitemap_videos': { ar: 'الفيديوهات', en: 'Videos' },
  'sitemap_photos': { ar: 'الصور', en: 'Photos' },
  'sitemap_infographics': { ar: 'الإنفوجرافيك', en: 'Infographics' },
  'sitemap_submit': { ar: 'تقديم شكوى', en: 'Submit Complaint' },
  'sitemap_track': { ar: 'تتبع الشكوى', en: 'Track Complaint' },
  'sitemap_previous': { ar: 'الشكاوى السابقة', en: 'Previous Complaints' },
  'sitemap_vision_mission': { ar: 'الرؤية والرسالة', en: 'Vision & Mission' },
  'sitemap_strategic_goals': { ar: 'الأهداف الاستراتيجية', en: 'Strategic Goals' },
  'sitemap_team': { ar: 'فريق العمل', en: 'Team' },
  'sitemap_statistics': { ar: 'الإحصائيات', en: 'Statistics' },
  'sitemap_reports': { ar: 'التقارير', en: 'Reports' },
  'sitemap_raw_data': { ar: 'البيانات الخام', en: 'Raw Data' },
  'nav_login': { ar: 'دخول المواطن', en: 'Citizen Login' },
  'nav_logout': { ar: 'تسجيل الخروج', en: 'Logout' },
  'nav_toggle_theme': { ar: 'تبديل السمة', en: 'Toggle Theme' },
  'sitemap_login': { ar: 'تسجيل الدخول', en: 'Login' },
  'sitemap_register': { ar: 'إنشاء حساب', en: 'Register' },
  'sitemap_dashboard': { ar: 'لوحة التحكم', en: 'Dashboard' },
  'sitemap_applications': { ar: 'شكاواي', en: 'My Complaints' },
  'sitemap_notifications': { ar: 'الإشعارات', en: 'Notifications' },
  'sitemap_civil_services': { ar: 'خدمات الأحوال المدنية', en: 'Civil Status Services' },
  'sitemap_financial': { ar: 'الخدمات المالية', en: 'Financial' },
  'sitemap_education': { ar: 'خدمات التعليم', en: 'Education' },
  'sitemap_health': { ar: 'خدمات الصحة', en: 'Health' },
  'sitemap_transportation': { ar: 'خدمات النقل', en: 'Transportation' },
  'sitemap_housing': { ar: 'خدمات الإسكان', en: 'Housing' },
  'sitemap_employment': { ar: 'خدمات العمل', en: 'Employment' },
  'sitemap_projects': { ar: 'خدمات المشاريع', en: 'Projects' },
  'sitemap_security': { ar: 'خدمات الأمن', en: 'Security' },
  'sitemap_environment': { ar: 'خدمات البيئة', en: 'Environment' },
  'sitemap_inquiry': { ar: 'خدمات الاستعلام', en: 'Inquiry' },
  'sitemap_support': { ar: 'خدمات الدعم', en: 'Support' },
  'sitemap_feedback': { ar: 'خدمات التقييم', en: 'Feedback' },

  // Directorate Detail
  'directorate_back': { ar: 'العودة إلى الدليل', en: 'Back to Directory' },
  'directorate_services': { ar: 'الخدمات المتاحة', en: 'Available Services' },
  'directorate_digital': { ar: 'خدمة  فورية', en: 'Instant Service' },
  'directorate_in_person': { ar: 'تتطلب مراجعة المركز', en: 'Requires center visit' },
  'directorate_no_services': { ar: 'لا توجد خدمات مضافة حالياً.', en: 'No services added currently.' },
  'directorate_paper_guide': { ar: 'عرض دليل المعاملات الورقية', en: 'View Paper Transactions Guide' },
  'directorate_news': { ar: 'آخر أخبار الوزارة', en: 'Latest Ministry News' },
  'directorate_contact': { ar: 'معلومات التواصل', en: 'Contact Information' },
  'directorate_address': { ar: 'دمشق - الجمارك مقابل الأمن الجنائي', en: 'Damascus - Customs, opposite Criminal Security' },
  'directorate_phone': { ar: '+963 11 222 3333', en: '+963 11 222 3333' },
  'directorate_email': { ar: 'contact@ministry.gov.sy', en: 'contact@ministry.gov.sy' },
  'directorate_website': { ar: 'www.ministry.gov.sy', en: 'www.ministry.gov.sy' },
  'contact_address_damascus': { ar: 'دمشق - الجمارك مقابل الأمن الجنائي', en: 'Damascus - Customs, opposite Criminal Security' },
  'directorate_hours': { ar: 'أوقات الدوام الرسمي', en: 'Official Working Hours' },
  'directorate_hours_sun_thu': { ar: 'الأحد - الخميس', en: 'Sunday - Thursday' },
  'directorate_hours_value': { ar: '08:00 ص - 03:30 م', en: '08:00 AM - 03:30 PM' },
  'directorate_fri_sat': { ar: 'الجمعة - السبت', en: 'Friday - Saturday' },
  'directorate_holiday': { ar: 'عطلة رسمية', en: 'Official Holiday' },
  'directorate_not_found': { ar: 'لم يتم العثور على الجهة', en: 'Directorate not found' },

  // General UI
  'ui_loading': { ar: 'جاري التحميل...', en: 'Loading...' },
  'ui_no_results': { ar: 'لا توجد نتائج مطابقة لبحثك', en: 'No matching results for your search' },
  'ui_show_all': { ar: 'عرض الكل', en: 'Show All' },
  'ui_close': { ar: 'إغلاق', en: 'Close' },
  'ui_save': { ar: 'حفظ', en: 'Save' },
  'ui_cancel': { ar: 'إلغاء', en: 'Cancel' },
  'ui_confirm': { ar: 'تأكيد', en: 'Confirm' },
  'ui_delete': { ar: 'حذف', en: 'Delete' },
  'ui_edit': { ar: 'تعديل', en: 'Edit' },
  'ui_view': { ar: 'عرض', en: 'View' },
  'ui_download': { ar: 'تحميل', en: 'Download' },
  'ui_upload': { ar: 'رفع', en: 'Upload' },
  'ui_search': { ar: 'بحث', en: 'Search' },
  'ui_filter': { ar: 'تصفية', en: 'Filter' },
  'ui_sort': { ar: 'ترتيب', en: 'Sort' },
  'ui_required': { ar: 'مطلوب', en: 'Required' },
  'ui_optional': { ar: 'اختياري', en: 'Optional' },
  'ui_yes': { ar: 'نعم', en: 'Yes' },
  'ui_no': { ar: 'لا', en: 'No' },
  'ui_submit': { ar: 'إرسال', en: 'Submit' },
  'ui_back': { ar: 'عودة', en: 'Back' },
  'ui_next': { ar: 'التالي', en: 'Next' },
  'ui_previous': { ar: 'السابق', en: 'Previous' },
  'ui_swipe': { ar: 'اسحب للمزيد', en: 'Swipe for more' },
  'ui_view_grid': { ar: 'عرض الشبكة', en: 'Grid View' },
  'ui_view_list': { ar: 'عرض القائمة', en: 'List View' },
  'ui_live': { ar: 'مباشر', en: 'Live' },
  'ui_ai': { ar: 'ذكاء اصطناعي', en: 'AI' },
  'ui_smart_summary': { ar: 'ملخص ذكي', en: 'Smart Summary' },
  'ui_smart_summarize': { ar: 'تلخيص ذكي', en: 'Smart Summarize' },
  'ui_analyzing': { ar: 'جاري التحليل...', en: 'Analyzing...' },
  'ui_hide_summary': { ar: 'إخفاء الملخص', en: 'Hide Summary' },
  'ui_exclusive_video': { ar: 'فيديو حصري', en: 'Exclusive Video' },
  'ui_writers': { ar: 'كاتب ومحلل', en: 'Writers & Analysts' },
  'ui_writers_desc': { ar: 'انضم إلى مجتمعنا من الخبراء والمحللين لقراءة تحليلات عميقة.', en: 'Join our community of experts and analysts for deep insights.' },
  'ui_browse_writers': { ar: 'تصفح الكتاب', en: 'Browse Writers' },
  'ui_exclusive_video_title': { ar: 'كواليس التحضيرات النهائية', en: 'Exclusive Behind the Scenes' },
  'ui_exclusive_video_desc': { ar: 'شاهد التقرير الحصري من قلب الحدث مع مراسلنا.', en: 'Watch the exclusive report from the heart of the event with our correspondent.' },
  'ui_breaking': { ar: 'عاجل', en: 'Breaking' },

  // Admin Dashboard
  'admin_panel': { ar: 'لوحة الإدارة', en: 'Admin Panel' },
  'admin_overview': { ar: 'نظرة عامة', en: 'Overview' },
  'admin_complaints': { ar: 'الشكاوى', en: 'Complaints' },
  'admin_content': { ar: 'إدارة المحتوى', en: 'Content Management' },
  'admin_users': { ar: 'المستخدمين', en: 'Users' },
  'admin_logout': { ar: 'تسجيل خروج', en: 'Logout' },
  'admin_search_placeholder': { ar: 'بحث سريع...', en: 'Quick search...' },
  'admin_total_complaints': { ar: 'إجمالي الشكاوى', en: 'Total Complaints' },
  'admin_new_complaints': { ar: 'الشكاوى الجديدة', en: 'New Complaints' },
  'admin_in_progress': { ar: 'قيد المعالجة', en: 'In Progress' },
  'admin_resolved': { ar: 'تم حلها', en: 'Resolved' },
  'admin_complaints_log': { ar: 'سجل الشكاوى الواردة', en: 'Incoming Complaints Log' },
  'admin_ticket_no': { ar: 'رقم التتبع', en: 'Tracking No.' },
  'admin_status': { ar: 'الحالة', en: 'Status' },
  'admin_last_update': { ar: 'التحديث الأخير', en: 'Last Update' },
  'admin_action': { ar: 'الإجراء', en: 'Action' },
  'admin_view': { ar: 'عرض', en: 'View' },
  'admin_add_new': { ar: 'إضافة جديد', en: 'Add New' },
  'admin_content_mgmt': { ar: 'إدارة المحتوى والمراسيم', en: 'Content & Decrees Management' },
  'admin_under_dev': { ar: 'قيد التطوير', en: 'Under Development' },

  // Quick Links Section
  'ql_title': { ar: 'روابط سريعة', en: 'Quick Links' },
  'ql_laws': { ar: 'القوانين والتشريعات', en: 'Laws & Legislation' },
  'ql_news': { ar: 'الأخبار', en: 'News' },
  'ql_announcements': { ar: 'الإعلانات', en: 'Announcements' },
  'ql_services': { ar: 'الخدمات', en: 'Services' },
  'ql_complaints': { ar: 'الشكاوى والمقترحات', en: 'Complaints & Suggestions' },
  'ql_faq': { ar: 'الأسئلة الشائعة', en: 'FAQ' },
  'ql_contact': { ar: 'اتصل بنا', en: 'Contact' },
  'ql_about': { ar: 'عن الوزارة', en: 'About' },
  'ql_directorates': { ar: 'الهيكل التنظيمي', en: 'Organizational Structure' },
  'ql_investment': { ar: 'الاستثمار', en: 'Investment' },
  'ql_media': { ar: 'المركز الإعلامي', en: 'Media Center' },

  // Central Directorate News
  'cdn_title': { ar: 'أخبار الوزارة', en: 'Ministry News' },
  'cdn_subtitle': { ar: 'آخر أخبار وأنشطة وزارة الاقتصاد والصناعة', en: 'Latest news and activities from the Ministry of Economy and Industry' },

  // News Section (grouped by directorate)
  'news_section_title': { ar: 'المركز الإعلامي', en: 'Media Center' },
  'news_section_subtitle': { ar: 'آخر الأخبار والمراسيم حسب المديريات', en: 'Latest news and decrees by directorates' },
  'show_more': { ar: 'عرض المزيد', en: 'Show More' },
  'no_news_currently': { ar: 'لا توجد أخبار حالياً.', en: 'No news currently.' },
  'featured_news': { ar: 'الخبر الرئيسي', en: 'Featured' },
  'latest_news': { ar: 'آخر الأخبار', en: 'Latest News' },
  'view_full_archive': { ar: 'عرض الأرشيف الكامل', en: 'View Full Archive' },

  // Newsletter Section
  'nl_badge': { ar: 'النشرة البريدية', en: 'Newsletter' },
  'nl_title': { ar: 'ابقَ على اطلاع بآخر المستجدات', en: 'Stay Updated with the Latest News' },
  'nl_subtitle': { ar: 'اشترك في نشرتنا البريدية للحصول على آخر الأخبار والقرارات والخدمات مباشرة إلى بريدك الإلكتروني', en: 'Subscribe to our newsletter to receive the latest news, decisions, and services directly to your inbox' },
  'nl_cta': { ar: 'اشتراك', en: 'Subscribe' },
  'nl_success': { ar: 'تم الاشتراك بنجاح!', en: 'Subscribed successfully!' },
  'nl_error': { ar: 'حدث خطأ. يرجى المحاولة مرة أخرى', en: 'An error occurred. Please try again' },

  // Footer Legal
  'footer_privacy': { ar: 'سياسة الخصوصية', en: 'Privacy Policy' },
  'footer_terms': { ar: 'شروط الاستخدام', en: 'Terms of Use' },

  // Search
  'search_clear': { ar: 'مسح', en: 'Clear' },
  'search_date_today': { ar: 'اليوم', en: 'Today' },
  'search_date_week': { ar: 'هذا الأسبوع', en: 'This Week' },
  'search_date_month': { ar: 'هذا الشهر', en: 'This Month' },
  'search_empty_title': { ar: 'لا توجد نتائج مطابقة', en: 'No matching results' },
  'search_empty_desc': { ar: 'جرب تغيير كلمات البحث أو الفلاتر المستخدمة', en: 'Try different keywords or adjust your filters' },
  'news_view_more': { ar: 'عرض المزيد', en: 'View More' },

  // User Dashboard
  'user_welcome': { ar: 'مرحباً،', en: 'Welcome,' },
  'user_logout': { ar: 'تسجيل الخروج', en: 'Logout' },
  'user_active_requests': { ar: 'الشكاوى النشطة', en: 'Active' },
  'user_completed_requests': { ar: 'المنجزة', en: 'Completed' },
  'user_rejected_requests': { ar: 'مرفوضة', en: 'Rejected' },
  'user_my_applications': { ar: 'شكاواي', en: 'My Complaints' },
  'user_notifications': { ar: 'الإشعارات', en: 'Notifications' },
  'user_settings': { ar: 'الإعدادات', en: 'Settings' },
  'user_recent_activity': { ar: 'آخر النشاطات', en: 'Recent Activity' },
  'user_quick_actions': { ar: 'إجراءات سريعة', en: 'Quick Actions' },
  'user_all_applications': { ar: 'جميع الشكاوى', en: 'All Complaints' },
  'user_new_request': { ar: 'طلب جديد', en: 'New Request' },
  'user_book_appt': { ar: 'حجز موعد', en: 'Book Appointment' },
  'user_track_request': { ar: 'تتبع الشكاوى', en: 'Track Complaints' },
  'user_tech_support': { ar: 'الدعم الفني', en: 'Support' },
  'user_account_settings': { ar: 'إعدادات الحساب', en: 'Account Settings' },
  'user_new_password_optional': { ar: 'كلمة المرور الجديدة (اختياري)', en: 'New Password (Optional)' },

  // Validation error messages (T002/T003)
  'validation_national_id_max': { ar: 'الرقم الوطني يجب ألا يتجاوز 11 خانة', en: 'National ID must not exceed 11 digits' },
  'validation_phone_max': { ar: 'رقم الهاتف يجب ألا يتجاوز 10 خانات', en: 'Phone number must not exceed 10 digits' },
  'validation_phone_invalid': { ar: 'يرجى إدخال رقم هاتف صالح متوافق مع رمز الدولة', en: 'Please enter a valid phone number matching the country code' },
  'validation_email_invalid': { ar: 'يرجى إدخال بريد إلكتروني صالح', en: 'Please enter a valid email address' },
  'validation_dob_invalid': { ar: 'يرجى إدخال تاريخ ميلاد صالح', en: 'Please enter a valid date of birth' },
  'validation_dob_future': { ar: 'تاريخ الميلاد لا يمكن أن يكون في المستقبل', en: 'Date of birth cannot be in the future' },
  'validation_dob_too_young': { ar: 'يجب أن يكون عمرك 13 سنة على الأقل', en: 'You must be at least 13 years old' },
  'validation_dob_too_old': { ar: 'يرجى إدخال تاريخ ميلاد واقعي', en: 'Please enter a realistic date of birth' },
  'validation_required': { ar: 'هذا الحقل مطلوب', en: 'This field is required' },
  'validation_password_mismatch': { ar: 'كلمات المرور غير متطابقة', en: 'Passwords do not match' },
  'error_generic': { ar: 'حدث خطأ. يرجى المحاولة مرة أخرى.', en: 'An error occurred. Please try again.' },
  'error_network': { ar: 'خطأ في الاتصال بالشبكة. يرجى التحقق من اتصالك.', en: 'Network connection error. Please check your connection.' },
  'expires_at_label': { ar: 'تاريخ الانتهاء', en: 'Expiry Date' },
  'expires_at_validation': { ar: 'تاريخ الانتهاء يجب أن يكون بعد تاريخ النشر', en: 'Expiry date must be after publish date' },
  'expires_at_validation_announcement': { ar: 'تاريخ انتهاء الصلاحية مطلوب للإعلانات', en: 'Expiry date is required for announcements' },
  'error_required_field': { ar: 'يرجى ملء جميع الحقول المطلوبة', en: 'Please fill in all required fields' },
  'newsletter_email_invalid': { ar: 'يرجى إدخال بريد إلكتروني صالح', en: 'Please enter a valid email address' },
  'newsletter_subscribe_error': { ar: 'حدث خطأ أثناء الاشتراك. يرجى المحاولة مرة أخرى.', en: 'An error occurred while subscribing. Please try again.' },
  'newsletter_subscribe_success': { ar: 'تم الاشتراك بنجاح', en: 'Subscribed successfully' },
  'newsletter_subscribe_failed': { ar: 'فشل الاشتراك', en: 'Subscription failed' },
  'newsletter_subscribed_message': { ar: 'تم الاشتراك بنجاح!', en: 'Subscribed successfully!' },
  'newsletter_title': { ar: 'النشرة البريدية', en: 'Newsletter' },
  'newsletter_description': { ar: 'اشترك للحصول على آخر الأخبار والتحديثات', en: 'Subscribe to get the latest news and updates' },
  'newsletter_placeholder': { ar: 'بريدك الإلكتروني', en: 'Your email' },
  'newsletter_subscribe_btn': { ar: 'اشتراك', en: 'Subscribe' },
  'newsletter_error_display': { ar: 'حدث خطأ. يرجى المحاولة مرة أخرى', en: 'An error occurred' },
  'complaint_template_label': { ar: 'نموذج الشكوى', en: 'Complaint Template' },
  'complaint_template_select': { ar: '-- اختر نموذج الشكوى --', en: '-- Select Complaint Template --' },
  'complaint_template_open': { ar: 'شكوى مفتوحة', en: 'Open Complaint' },
  'complaint_anonymous': { ar: 'شكوى من مجهول', en: 'Anonymous Complaint' },

  // Complaint Home Section
  'complaints_section_badge': { ar: 'خدمة المواطن', en: 'Citizen Service' },
  'complaints_section_title': { ar: 'صوتك مسموع', en: 'Your Voice Matters' },
  'complaints_section_desc': {
    ar: 'منصة رقمية آمنة تتيح لك تقديم الشكاوى ومتابعتها بكل شفافية وفاعلية لضمان حقوقك وتحسين جودة الخدمات.',
    en: 'A secure digital platform allowing you to submit and track complaints with transparency and efficiency to ensure your rights and improve service quality.'
  },
  'submit_complaint': { ar: 'تقديم شكوى', en: 'Submit Complaint' },
  'track_complaint': { ar: 'متابعة طلب', en: 'Track Request' },
  'complaints_stat': { ar: 'نسبة الاستجابة للشكاوى الواردة', en: 'Response rate to incoming complaints' },

  // Complaint Portal Misc






  // Announcements


  'announcements_portal_badge': { ar: 'البوابة الرسمية', en: 'Official Portal' },
  'filter_active': { ar: 'النشطة', en: 'Active' },
  'filter_all_types': { ar: 'جميع الأنواع', en: 'All Types' },
  'filter_all_categories': { ar: 'جميع التصنيفات', en: 'All Categories' },
  'filter_expired': { ar: 'المنتهية', en: 'Expired' },
  'announcements_count': { ar: 'عرض {shown} من {total} إعلان', en: 'Showing {shown} of {total} announcements' },
  'period_label': { ar: 'الفترة', en: 'Period' },
  'month_label': { ar: 'الشهر', en: 'Month' },
  'year_label': { ar: 'السنة', en: 'Year' },
  'filter_clear': { ar: 'مسح', en: 'Clear' },
  'announcements_no_results': { ar: 'لا توجد إعلانات', en: 'No Announcements Found' },
  'announcements_try_search': { ar: 'جرب تغيير معايير البحث', en: 'Try changing your search criteria' },
  'announcements_details': { ar: 'التفاصيل', en: 'Details' },
  'announcements_faq_title': { ar: 'الأسئلة الشائعة', en: 'Frequently Asked Questions' },
  'announcements_faq_q1': { ar: 'كيف أتابع الإعلانات الجديدة؟', en: 'How do I follow new announcements?' },
  'announcements_faq_a1': { ar: 'يمكنك زيارة هذه الصفحة بانتظام أو الاشتراك في النشرة البريدية للحصول على إشعارات بالإعلانات الجديدة.', en: 'You can visit this page regularly or subscribe to the newsletter for new announcement notifications.' },
  'announcements_faq_q2': { ar: 'ما الفرق بين أنواع الإعلانات؟', en: 'What is the difference between announcement types?' },
  'announcements_faq_a2': { ar: 'تتنوع الإعلانات بين عاجلة وهامة ومناقصات ووظائف وعامة، ويمكنك تصفيتها باستخدام القوائم أعلاه.', en: 'Announcements vary between urgent, important, tenders, jobs, and general. You can filter them using the menus above.' },
  'announcements_view_all_faq': { ar: 'عرض جميع الأسئلة الشائعة', en: 'View all FAQs' },

  // Announcement Types & Categories (for filters)
  'type_urgent': { ar: 'عاجل', en: 'Urgent' },
  'type_important': { ar: 'هام', en: 'Important' },
  'type_tender': { ar: 'مناقصات', en: 'Tenders' },
  'type_job': { ar: 'توظيف', en: 'Jobs' },
  'type_general': { ar: 'عام', en: 'General' },
  'cat_tender': { ar: 'مناقصات', en: 'Tenders' },
  'cat_job': { ar: 'توظيف', en: 'Employment' },
  'cat_training': { ar: 'تدريب', en: 'Training' },
  'cat_tech': { ar: 'تقنية', en: 'Technology' },
  'cat_admin': { ar: 'إداري', en: 'Administrative' },
  'cat_finance': { ar: 'تمويل', en: 'Finance' },
  'complaint_identified': { ar: 'شكوى من معلوم', en: 'Identified Complaint' },
  'complaint_type_label': { ar: 'نوع الشكوى', en: 'Complaint Type' },

  // 2FA page translations
  'twofa_title': { ar: 'المصادقة الثنائية', en: 'Two-Factor Authentication' },
  'twofa_subtitle': { ar: 'تم إرسال رمز التحقق إلى بريدك الإلكتروني', en: 'A verification code has been sent to your email' },
  'twofa_code_label': { ar: 'رمز التحقق', en: 'Verification Code' },
  'twofa_code_placeholder': { ar: 'أدخل الرمز المكون من 6 أرقام', en: 'Enter the 6-digit code' },
  'twofa_verify': { ar: 'تحقق', en: 'Verify' },
  'twofa_resend': { ar: 'إعادة إرسال الرمز', en: 'Resend Code' },
  'twofa_resend_success': { ar: 'تم إعادة إرسال الرمز بنجاح', en: 'Code resent successfully' },
  'twofa_invalid_code': { ar: 'رمز التحقق غير صحيح', en: 'Invalid verification code' },
  'twofa_expired': { ar: 'انتهت صلاحية الرمز. يرجى طلب رمز جديد.', en: 'Code has expired. Please request a new one.' },
  'twofa_rate_limited': { ar: 'محاولات كثيرة جداً. يرجى الانتظار قبل المحاولة مرة أخرى.', en: 'Too many attempts. Please wait before trying again.' },
  'twofa_resend_rate_limited': { ar: 'تم إرسال الرمز مؤخراً. يرجى الانتظار قبل إعادة الإرسال.', en: 'Code was sent recently. Please wait before resending.' },
  'twofa_resend_failed': { ar: 'فشل إعادة إرسال الرمز. يرجى المحاولة مرة أخرى.', en: 'Failed to resend code. Please try again.' },
  'twofa_resend_cooldown': { ar: 'إعادة الإرسال بعد {seconds} ثانية', en: 'Resend in {seconds}s' },
  'twofa_too_many_attempts': { ar: 'تم تجاوز عدد المحاولات المسموحة. يرجى طلب رمز جديد.', en: 'Too many failed attempts. Please request a new code.' },
  'twofa_locked_out': { ar: 'تم قفل التحقق بسبب كثرة المحاولات الفاشلة. يرجى إعادة إرسال رمز جديد للمتابعة.', en: 'Verification locked due to too many failed attempts. Please resend a new code to continue.' },
  'twofa_attempts_warning': { ar: 'تبقى {remaining} محاولات قبل القفل', en: '{remaining} attempts remaining before lockout' },

  // Profile email edit translations
  'profile_edit_email': { ar: 'تعديل البريد الإلكتروني', en: 'Edit Email' },
  'profile_new_email': { ar: 'البريد الإلكتروني الجديد', en: 'New Email Address' },
  'profile_current_password': { ar: 'كلمة المرور الحالية', en: 'Current Password' },
  'profile_email_verify_sent': { ar: 'تم إرسال رمز التحقق إلى بريدك الإلكتروني الجديد', en: 'Verification code sent to your new email' },
  'profile_email_updated': { ar: 'تم تحديث البريد الإلكتروني بنجاح', en: 'Email updated successfully' },
  'profile_email_exists': { ar: 'هذا البريد الإلكتروني مستخدم بالفعل', en: 'This email is already in use' },
  'profile_send_verification': { ar: 'إرسال رمز التحقق', en: 'Send Verification Code' },
  'profile_verify_code': { ar: 'رمز التحقق', en: 'Verification Code' },
  'profile_verify_code_placeholder': { ar: 'أدخل الرمز المكون من 6 أرقام', en: 'Enter 6-digit code' },
  'profile_verify_and_update': { ar: 'تحقق وتحديث البريد', en: 'Verify & Update Email' },
  'profile_cancel': { ar: 'إلغاء', en: 'Cancel' },
  'profile_sending': { ar: 'جاري الإرسال...', en: 'Sending...' },
  'profile_verifying': { ar: 'جاري التحقق...', en: 'Verifying...' },
  'profile_resend_code': { ar: 'إعادة إرسال الرمز', en: 'Resend Code' },

  // News section directorate titles
  'news_ministry': { ar: 'أخبار الوزارة', en: 'Ministry News' },
  'news_industry': { ar: 'أخبار الإدارة العامة للصناعة', en: 'General Directorate of Industry News' },
  'news_commerce': { ar: 'أخبار الإدارة العامة للاقتصاد', en: 'General Directorate of Economy News' },
  'news_internal_trade': { ar: 'أخبار الإدارة العامة للتجارة الداخلية وحماية المستهلك', en: 'General Directorate of Internal Trade and Consumer Protection News' },

  // Contact address update
  'contact_address_ministry': { ar: 'دمشق - الجمارك مقابل الأمن الجنائي', en: 'Damascus - Customs, opposite Criminal Security' },
  // Complaint Portal - Additional
  'complaint_loaded_success': { ar: 'تم تحميل القالب بنجاح', en: 'Template loaded successfully' },
  'complaint_delete_error_status': { ar: 'يمكن حذف الشكاوى فقط في حالة "مستلمة"', en: 'Only complaints with "received" status can be deleted' },
  'complaint_delete_not_allowed': { ar: 'لا يمكن حذف الشكوى', en: 'Cannot delete complaint' },
  'complaint_delete_success': { ar: 'تم حذف الشكوى بنجاح', en: 'Complaint deleted successfully' },

  // Header Actions
  'header_search': { ar: 'بحث', en: 'Search' },
  'header_theme': { ar: 'المظهر', en: 'Theme' },
  'header_lang': { ar: 'اللغة', en: 'Language' },
  'complaint_delete_failed': { ar: 'فشل حذف الشكوى', en: 'Failed to delete complaint' },
  'complaint_delete_error_generic': { ar: 'حدث خطأ أثناء حذف الشكوى', en: 'An error occurred while deleting the complaint' },
  'complaint_delete_btn': { ar: 'حذف الشكوى', en: 'Delete Complaint' },
  'complaint_false_info_warning': { ar: 'الشكاوى الكاذبة سيتم إلغاؤها وقد تؤدي للمساءلة القانونية', en: 'False complaints will be cancelled and may result in legal accountability' },
  'complaint_accurate_info_required': { ar: 'يجب تقديم معلومات صحيحة.', en: 'You must provide accurate information.' },
  'complaint_review_guidelines': { ar: 'ضوابط النظر في الشكاوى', en: 'Complaint Review Guidelines' },
  'complaint_review_desc': { ar: 'يتم النظر في الشكاوى بجدية بعد التأكد من وضوحها وكفاية البيانات الواردة فيها', en: 'Complaints are reviewed seriously after confirming their clarity and sufficiency of provided data' },
  'complaint_condition_intro_review': { ar: 'لن يتم النظر في الشكوى في الحالات التالية:', en: 'Complaints will NOT be reviewed if:' },
  'complaint_condition_1': { ar: 'إذا كانت غير واضحة أو تفتقر إلى البيانات الكافية', en: 'If unclear or lacking sufficient data' },
  'complaint_condition_2': { ar: 'إذا تبين أنها كيدية', en: 'If found to be malicious or vindictive' },
  'complaint_condition_3': { ar: 'إذا سبق التحقيق فيها', en: 'If previously investigated' },
  'complaint_condition_4': { ar: 'إذا كانت خارج نطاق اختصاص وزارة الاقتصاد والصناعة', en: 'If outside the jurisdiction of the Ministry of Economy and Industry' },
  'date_from': { ar: 'من تاريخ', en: 'From Date' },
  'date_to': { ar: 'إلى تاريخ', en: 'To Date' },
  'download_attachments': { ar: 'الملفات المرفقة', en: 'Attachments' },
  'download_pdf': { ar: 'تحميل PDF', en: 'Download PDF' },
  'complaint_agree_terms': { ar: 'أوافق على الضوابط المذكورة أعلاه', en: 'I agree to the terms mentioned above' },
  'complaint_start_new': { ar: 'بدء تقديم شكوى جديدة', en: 'Start New Complaint' },
  'complaint_back_terms': { ar: 'العودة للضوابط', en: 'Back to Terms' },
  'complaint_use_template': { ar: 'استخدام قالب', en: 'Use Template' },
  'complaint_my_data': { ar: 'بياناتي المسجلة', en: 'My Registered Data' },
  'complaint_known_identity': { ar: 'معروف الهوية', en: 'Known Identity' },
  'complaint_anonymous_identity': { ar: 'مجهول الهوية', en: 'Anonymous' },
  'complaint_ocr_attach': { ar: 'أرفق صورة للشكوى المكتوبة (OCR)', en: 'Attach complaint image (OCR)' },
  'complaint_ocr_auto_extract': { ar: 'سيتم استخراج النص تلقائياً من الصورة', en: 'Text will be extracted automatically from the image' },
  'complaint_ocr_processing': { ar: 'جاري المعالجة...', en: 'Processing...' },
  'complaint_ocr_extracted': { ar: 'تم الاستخراج', en: 'Extracted' },
  'complaint_upload_attach_ocr': { ar: '[تم استخراج النص تلقائياً من المستند المرفق]: \n', en: '[Text extracted automatically from attached document]: \n' },
  'complaint_prev_related': { ar: 'هل هذه الشكوى مرتبطة بشكوى سابقة؟', en: 'Is this complaint related to a previous one?' },
  'complaint_prev_ticket': { ar: 'رقم تتبع الشكوى السابقة', en: 'Previous Tracking Number' },
  'complaint_prev_ticket_hint': { ar: 'يرجى إدخال رقم تتبع الشكوى السابقة لربطها بهذه الشكوى وتسريع المعالجة.', en: 'Please enter the previous tracking number to link it to this complaint and speed up processing.' },
  'complaint_submit_fail': { ar: 'فشل إرسال الشكوى', en: 'Failed to submit complaint' },
  'complaint_try_again': { ar: 'يرجى المحاولة مرة أخرى', en: 'Please try again' },
  'complaint_found': { ar: 'تم العثور على الشكوى', en: 'Complaint found' },
  'complaint_status_label': { ar: 'حالة الشكوى:', en: 'Complaint Status:' },
  'complaint_verify_ticket_id': { ar: 'تأكد من صحة رقم تتبع الشكوى والرقم الوطني', en: 'Please verify the tracking number and national ID' },
  'complaint_connection_error': { ar: 'خطأ في الاتصال', en: 'Connection error' },
  'complaint_connection_error_desc': { ar: 'حدث خطأ أثناء الاتصال بالنظام', en: 'An error occurred while connecting to the system' },
  'complaint_need_help': { ar: 'هل تحتاج للمساعدة المباشرة؟', en: 'Need direct help?' },
  'complaint_whatsapp': { ar: 'تواصل عبر واتساب', en: 'Contact via WhatsApp' },
  'complaint_templates_title': { ar: 'قوالب الشكاوى الجاهزة', en: 'Ready Complaint Templates' },
  'complaint_no_templates': { ar: 'لا توجد قوالب متاحة حالياً', en: 'No templates available currently' },
  'complaint_loading_templates': { ar: 'جاري تحميل أنواع الشكاوى...', en: 'Loading complaint types...' },

  // Suggestion Portal
  'suggestion_portal_title': { ar: 'بوابة المقترحات', en: 'Suggestions Portal' },
  'suggestion_submit_tab': { ar: 'تقديم مقترح جديد', en: 'Submit New Suggestion' },
  'suggestion_track_tab': { ar: 'متابعة حالة المقترح', en: 'Track Suggestion' },
  'suggestion_terms_title': { ar: 'المقترحات', en: 'Suggestions' },
  'suggestion_terms_info': { ar: 'نرحب بمقترحاتكم لتطوير وتحسين خدمات وزارة الاقتصاد والصناعة', en: 'We welcome your suggestions to develop and improve the services of the Ministry of Economy and Industry' },
  'suggestion_terms_guidelines': { ar: 'ضوابط تقديم المقترحات', en: 'Suggestion Submission Guidelines' },
  'suggestion_terms_desc': { ar: 'يتم دراسة جميع المقترحات الواردة بعناية من قبل الفريق المختص', en: 'All submitted suggestions are carefully reviewed by the relevant team' },
  'suggestion_condition_intro': { ar: 'يرجى مراعاة التالي عند تقديم مقترحكم:', en: 'Please consider the following when submitting your suggestion:' },
  'suggestion_condition_1': { ar: 'أن يكون المقترح واضحاً ومحدداً', en: 'The suggestion should be clear and specific' },
  'suggestion_condition_2': { ar: 'أن يكون ضمن اختصاصات وزارة الاقتصاد والصناعة', en: 'It should be within the jurisdiction of the Ministry of Economy and Industry' },
  'suggestion_condition_3': { ar: 'أن يتضمن وصفاً كافياً للفكرة المقترحة', en: 'It should include a sufficient description of the proposed idea' },
  'suggestion_agree_terms': { ar: 'أوافق على الضوابط المذكورة أعلاه', en: 'I agree to the guidelines mentioned above' },
  'suggestion_start_new': { ar: 'بدء تقديم مقترح جديد', en: 'Start New Suggestion' },
  'suggestion_back_terms': { ar: 'العودة إلى الشروط', en: 'Back to Terms' },
  'suggestion_step_terms': { ar: 'الشروط', en: 'Terms' },
  'suggestion_step_identity': { ar: 'الهوية', en: 'Identity' },
  'suggestion_step_details': { ar: 'التفاصيل', en: 'Details' },
  'suggestion_form_title': { ar: 'نموذج تقديم المقترحات', en: 'Suggestion Submission Form' },
  'suggestion_form_subtitle': { ar: 'شاركنا أفكارك لتطوير خدماتنا', en: 'Share your ideas to improve our services' },
  'suggestion_first_name': { ar: 'الاسم الأول', en: 'First Name' },
  'suggestion_last_name': { ar: 'الاسم الأخير', en: 'Last Name' },
  'suggestion_father_name': { ar: 'اسم الأب', en: 'Father Name' },
  'suggestion_name': { ar: 'الاسم الكامل', en: 'Full Name' },
  'suggestion_job_title': { ar: 'المسمى الوظيفي', en: 'Job Title' },
  'suggestion_email': { ar: 'البريد الإلكتروني', en: 'Email Address' },
  'suggestion_phone': { ar: 'رقم الهاتف', en: 'Phone Number' },
  'suggestion_directorate': { ar: 'الجهة المعنية', en: 'Target Directorate' },
  'suggestion_directorate_placeholder': { ar: '-- اختر الجهة المعنية --', en: '-- Select Directorate --' },
  'suggestion_description': { ar: 'تفاصيل المقترح', en: 'Suggestion Details' },
  'suggestion_description_placeholder': { ar: 'اشرح مقترحك بالتفصيل...', en: 'Describe your suggestion in detail...' },
  'suggestion_attachments': { ar: 'المرفقات', en: 'Attachments' },
  'suggestion_attachments_hint': { ar: 'اضغط لرفع ملفات أو قم بسحبها وإفلاتها هنا', en: 'Click to upload files or drag and drop here' },
  'suggestion_attachments_types': { ar: 'PDF, DOC, JPG, PNG (حد أقصى 5 ملفات)', en: 'PDF, DOC, JPG, PNG (Max 5 files)' },
  'suggestion_submit': { ar: 'إرسال المقترح', en: 'Submit Suggestion' },
  'suggestion_sending': { ar: 'جاري الإرسال...', en: 'Sending...' },
  'suggestion_success': { ar: 'تم استلام مقترحك بنجاح', en: 'Suggestion Received Successfully' },
  'suggestion_success_desc': { ar: 'نشكرك على مساهمتك في تحسين خدماتنا. يرجى الاحتفاظ برقم المتابعة أدناه.', en: 'Thank you for contributing to improving our services. Please keep the tracking number below.' },
  'suggestion_tracking_number': { ar: 'رقم المتابعة', en: 'Tracking Number' },
  'suggestion_track_now': { ar: 'متابعة المقترح الآن', en: 'Track Suggestion Now' },
  'suggestion_track_title': { ar: 'متابعة المقترحات', en: 'Track Suggestions' },
  'suggestion_track_subtitle': { ar: 'أدخل رقم المتابعة للاستعلام عن حالة مقترحك', en: 'Enter the tracking number to check your suggestion status' },
  'suggestion_track_placeholder': { ar: 'مثال: SUG-12345', en: 'Example: SUG-12345' },
  'suggestion_not_found': { ar: 'لم يتم العثور على مقترح بهذا الرقم', en: 'No suggestion found with this number' },
  'suggestion_submit_fail': { ar: 'فشل إرسال المقترح', en: 'Failed to submit suggestion' },
  'suggestion_required_fields': { ar: 'يرجى ملء الحقول الإلزامية', en: 'Please fill in the required fields' },
  'suggestion_optional': { ar: 'اختياري', en: 'Optional' },
  'suggestion_hero_title': { ar: 'نستمع إليك .. لنبني المستقبل', en: 'We Listen to You.. To Build the Future' },
  'suggestion_hero_subtitle': { ar: 'تولي وزارة الاقتصاد أهمية بالغة لمقترحاتكم وأفكاركم', en: 'The Ministry of Economy values your suggestions and ideas' },
  'suggestion_have_complaint': { ar: 'هل لديك شكوى؟', en: 'Have a complaint?' },
  'suggestion_complaint_desc': { ar: 'يمكنك تقديم شكوى عبر منظومة الشكاوى الإلكترونية', en: 'You can submit a complaint through the electronic complaints system' },
  'suggestion_go_complaints': { ar: 'تقديم شكوى', en: 'Submit Complaint' },
  'complaint_have_suggestion': { ar: 'هل لديك مقترح لتطوير خدماتنا؟', en: 'Have a suggestion to improve our services?' },
  'complaint_suggestion_desc': { ar: 'شاركنا أفكارك ومقترحاتك لتحسين الخدمات المقدمة', en: 'Share your ideas and suggestions to improve the services provided' },
  'complaint_go_suggestions': { ar: 'تقديم مقترح', en: 'Submit Suggestion' },
  // ContactSection
  'contact_us_title': { ar: 'تواصل معنا', en: 'Contact Us' },
  'contact_us_description': { ar: 'نحن هنا لخدمتك. يمكنك التواصل معنا عبر النموذج الإلكتروني الموحد أو عبر قنوات الاتصال الرسمية.', en: 'We are here to serve you. Contact us through the unified electronic form or official channels.' },
  'contact_info_title': { ar: 'معلومات الاتصال', en: 'Contact Information' },
  'contact_info_description': { ar: 'للاستفسارات العاجلة، يرجى الاتصال بمركز خدمة المواطن الموحد. فريقنا جاهز للرد على استفساراتكم على مدار الساعة.', en: 'For urgent inquiries, please call the unified citizen service center. Our team is ready to respond around the clock.' },
  'contact_hotline_label': { ar: 'الخط الساخن الموحد', en: 'Unified Hotline' },

  'contact_address_label': { ar: 'المقر الرئيسي', en: 'Headquarters' },
  'contact_working_hours_label': { ar: 'ساعات العمل', en: 'Working Hours' },

  'contact_form_success_title': { ar: 'تم إرسال رسالتك بنجاح', en: 'Your message was sent successfully' },
  'contact_form_success_message': { ar: 'سيتم الرد على استفسارك خلال 24 ساعة عمل.', en: 'Your inquiry will be responded to within 24 business hours.' },
  'contact_form_name': { ar: 'الاسم الكامل', en: 'Full Name' },
  'contact_form_email': { ar: 'البريد الإلكتروني', en: 'Email Address' },
  'contact_form_subject': { ar: 'عنوان الرسالة', en: 'Message Subject' },
  'contact_form_department': { ar: 'الجهة المختصة', en: 'Department' },
  'contact_form_select_dept': { ar: '-- اختر الجهة --', en: '-- Select Department --' },
  'contact_form_general': { ar: 'الاستعلامات العامة', en: 'General Inquiries' },
  'contact_form_complaints': { ar: 'مكتب الشكاوى', en: 'Complaints Office' },
  'contact_form_media': { ar: 'المكتب الإعلامي', en: 'Media Office' },
  'contact_form_message': { ar: 'نص الرسالة', en: 'Message' },
  'contact_form_sending': { ar: 'جاري الإرسال...', en: 'Sending...' },
  'contact_form_submit': { ar: 'إرسال الرسالة', en: 'Send Message' },
  // HeroGrid
  'hero_live_badge': { ar: 'مباشر', en: 'Live' },
  'hero_ai_label': { ar: 'ذكاء اصطناعي', en: 'AI Powered' },
  'hero_smart_summary': { ar: 'ملخص ذكي', en: 'Smart Summary' },
  'hero_read_more': { ar: 'اقرأ المزيد', en: 'Read More' },
  'hero_analyzing': { ar: 'جاري التحليل...', en: 'Analyzing...' },
  'hero_hide_summary': { ar: 'إخفاء الملخص', en: 'Hide Summary' },
  'hero_summarize': { ar: 'تلخيص ذكي', en: 'AI Summarize' },
  // SatisfactionRating
  'rating_error': { ar: 'فشل إرسال التقييم. يرجى المحاولة مرة أخرى.', en: 'Failed to submit rating. Please try again.' },
  'rating_connection_error': { ar: 'حدث خطأ أثناء الاتصال بالنظام.', en: 'A connection error occurred.' },
  'rating_thank_you': { ar: 'شكراً لتقييمك!', en: 'Thank you for your rating!' },
  'rating_appreciation': { ar: 'نقدر ملاحظاتك وتساعدنا في تحسين خدماتنا.', en: 'We appreciate your feedback, it helps us improve our services.' },
  'rating_title': { ar: 'كيف كانت تجربتك؟', en: 'How was your experience?' },
  'rating_instruction': { ar: 'يرجى تقييم جودة التعامل وسرعة الإنجاز بعد حل الشكوى.', en: 'Please rate the quality of handling and speed of resolution.' },
  'rating_comments_label': { ar: 'ملاحظات إضافية (اختياري)', en: 'Additional comments (optional)' },
  'rating_comments_placeholder': { ar: 'أخبرنا المزيد عن تجربتك...', en: 'Tell us more about your experience...' },
  'rating_sending': { ar: 'جاري الإرسال...', en: 'Sending...' },
  'rating_submit': { ar: 'إرسال التقييم', en: 'Submit Rating' },
  // UI Amendments - Additional translations
  'view_all': { ar: 'عرض الكل', en: 'View All' },
  'copied': { ar: 'تم النسخ', en: 'Copied' },
  'ai_summary': { ar: 'ملخص ذكي', en: 'AI Summary' },
  'loading_summary': { ar: 'جاري التلخيص...', en: 'Generating summary...' },
  'share': { ar: 'مشاركة', en: 'Share' },
  'link_copied': { ar: 'تم نسخ الرابط', en: 'Link copied' },
  'general_form': { ar: 'النموذج العام', en: 'General Form' },
  'suggestion_failed': { ar: 'فشل في تقديم الاقتراح', en: 'Failed to submit suggestion' },
  'published_at': { ar: 'نُشر في', en: 'Published at' },
  'time_ago': { ar: 'منذ', en: 'ago' },
  'title_ar_hint': { ar: 'مثال: مناقصة عامة لتوريد معدات', en: 'Example: General tender for equipment supply' },
  'title_ar_required': { ar: 'يرجى إدخال عنوان الإعلان بالعربية', en: 'Please enter announcement title in Arabic' },

  'directorates_subtitle': { ar: 'الإدارات العامة لوزارة الاقتصاد والصناعة', en: 'General Directorates of the Ministry of Economy and Industry' },
  'directorate_subtitle': { ar: 'إدارة عامة', en: 'General Directorate' },
  'newsletter_subscribed': { ar: 'تم الاشتراك بنجاح في النشرة الإخبارية', en: 'Successfully subscribed to the newsletter' },
  'print': { ar: 'طباعة', en: 'Print' },
  'current_password_required': { ar: 'كلمة المرور الحالية مطلوبة', en: 'Current password is required' },
  'my_complaints': { ar: 'شكاواي', en: 'My Complaints' },
  'no_complaints': { ar: 'لا توجد شكاوى مسجلة', en: 'No complaints registered' },
  'clear_filters': { ar: 'مسح الفلاتر', en: 'Clear Filters' },

  // T050: Newsletter additional translations
  'newsletter_subtitle': { ar: 'اشترك ليصلك كل جديد', en: 'Subscribe to stay updated' },
  'newsletter_subscribe': { ar: 'اشتراك', en: 'Subscribe' },
  'newsletter_success': { ar: 'تم الاشتراك بنجاح! شكراً لك.', en: 'Successfully subscribed! Thank you.' },
  'newsletter_error': { ar: 'حدث خطأ. يرجى المحاولة مرة أخرى.', en: 'An error occurred. Please try again.' },
  'newsletter_invalid_email': { ar: 'يرجى إدخال بريد إلكتروني صالح.', en: 'Please enter a valid email address.' },

  // T051: Complaint general form translations
  'complaint_type': { ar: 'نوع الشكوى', en: 'Complaint Type' },
  'complaint_select_type': { ar: '-- اختر نوع الشكوى --', en: '-- Select Complaint Type --' },
  'complaint_address': { ar: 'العنوان', en: 'Address' },
  'complaint_attachments': { ar: 'المرفقات', en: 'Attachments' },
  'complaint_attach_files': { ar: 'أرفق ملفات (اختياري)', en: 'Attach files (optional)' },
  'complaint_max_size': { ar: 'الحد الأقصى للملف 5 ميغابايت', en: 'Maximum file size 5MB' },
  'complaint_terms': { ar: 'أقر بصحة المعلومات المقدمة', en: 'I confirm the accuracy of the provided information' },
  'complaint_status_received': { ar: 'واردة', en: 'Received' },
  'complaint_status_completed': { ar: 'منتهية', en: 'Completed' },

  // T052: Announcements page translations
  'announcements_all_types': { ar: 'جميع الأنواع', en: 'All Types' },
  'announcements_all_categories': { ar: 'جميع التصنيفات', en: 'All Categories' },
  'announcements_urgent': { ar: 'عاجل', en: 'Urgent' },
  'announcements_important': { ar: 'هام', en: 'Important' },
  'announcements_tender': { ar: 'مناقصة', en: 'Tender' },
  'announcements_job': { ar: 'توظيف', en: 'Job' },
  'announcements_general': { ar: 'إعلان', en: 'Announcement' },
  'announcement_active': { ar: 'نشط', en: 'Active' },
  'announcement_expired': { ar: 'انتهى التقديم', en: 'Application Closed' },
  'announcement_expired_on': { ar: 'انتهى بتاريخ', en: 'Expired on' },
  'announcement_expires_on': { ar: 'ينتهي بتاريخ', en: 'Expires on' },

  'announcements_empty': { ar: 'لا توجد إعلانات', en: 'No Announcements Found' },
  'announcements_empty_desc': { ar: 'جرب تغيير معايير البحث', en: 'Try changing your search criteria' },

  // Civil Registry & National ID Field
  'civil_registry_verifying': { ar: 'جارٍ التحقق من السجل المدني...', en: 'Verifying with civil registry...' },
  'civil_registry_verified': { ar: 'تم التحقق من الرقم الوطني بنجاح في السجل المدني', en: 'National ID verified successfully with civil registry' },
  'civil_registry_not_found': { ar: 'الرقم الوطني غير مسجل في السجل المدني. يرجى التحقق من صحة الرقم المدخل.', en: 'National ID not found in civil registry. Please verify the entered number.' },
  'civil_registry_mismatch': { ar: 'البيانات المدخلة غير مطابقة للسجل المدني', en: 'Entered data does not match civil registry records' },
  'civil_registry_error': { ar: 'حدث خطأ أثناء الاتصال بخدمة السجل المدني. يرجى المحاولة مرة أخرى.', en: 'Error connecting to civil registry service. Please try again.' },
  'civil_registry_unavailable': { ar: 'خدمة التحقق من السجل المدني غير متاحة حالياً', en: 'Civil registry verification service is currently unavailable' },
  'civil_registry_auto_fill': { ar: 'تم تعبئة البيانات تلقائياً من السجل المدني', en: 'Data auto-filled from civil registry' },
  'national_id_format_error': { ar: 'الرقم الوطني يجب أن يتكون من 11 رقماً فقط', en: 'National ID must be exactly 11 digits' },
  'national_id_already_registered': { ar: 'الرقم الوطني مسجل مسبقاً في النظام', en: 'This National ID is already registered in the system' },
  'national_id_numeric_only': { ar: 'الرقم الوطني يجب أن يحتوي على أرقام فقط', en: 'National ID must contain numbers only' },
  'national_id_verify_button': { ar: 'تحقق من السجل المدني', en: 'Verify with Civil Registry' },
  'national_id_chars_remaining': { ar: 'رقم متبقي', en: 'digits remaining' },
  'national_id_counter': { ar: 'أرقام', en: 'digits' },
};


const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

export const LanguageProvider: React.FC<{ children: ReactNode }> = ({ children }) => {
  const [language, setLanguage] = useState<Language>('ar');
  const [hydrated, setHydrated] = useState(false);

  const direction = language === 'ar' ? 'rtl' : 'ltr';

  // Sync from localStorage after hydration to avoid mismatch
  useEffect(() => {
    const saved = localStorage.getItem('gov_lang') as Language | null;
    if (saved && saved !== language) {
      setLanguage(saved);
    }
    setHydrated(true);
  }, []); // eslint-disable-line react-hooks/exhaustive-deps

  useEffect(() => {
    if (!hydrated) return;
    localStorage.setItem('gov_lang', language);
    document.documentElement.setAttribute('dir', direction);
    document.documentElement.setAttribute('lang', language);

    if (language === 'en') {
      document.body.classList.add('font-english');
    } else {
      document.body.classList.remove('font-english');
    }
  }, [language, direction, hydrated]);

  const toggleLanguage = () => {
    setLanguage(prev => prev === 'ar' ? 'en' : 'ar');
  };

  const t = (key: string) => {
    return translations[key]?.[language] || key;
  };

  return (
    <LanguageContext.Provider value={{ language, direction, toggleLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  );
};

export const useLanguage = () => {
  const context = useContext(LanguageContext);
  if (context === undefined) {
    throw new Error('useLanguage must be used within a LanguageProvider');
  }
  return context;
};
